/*                                                                             
               SAS DATA DEFINITION STATEMENTS FOR ICPSR 7441                   
                    SURVEY OF CONSUMER FINANCES, 1961                          
                          NOVEMBER 1977 VERSION                                
                                                                               
   The following SAS setup sections may appear in this file for the LRECL      
   version of this data collection.  These sections are listed below:          
                                                                               
   PROC FORMAT, in these statements, creates user-defined labels as            
   formats for variable values.   Formats replace original values with the     
   user-defined labels in subsequent SAS procedures once the formats           
   are assigned to a variable by the FORMAT command in the DATA step.          
   Not all variables necessarily have user-defined formats.                    
                                                                               
   DATA begins a SAS data step and names an output SAS dataset.                
                                                                               
   INFILE identifies the input file to be read with the input statement.       
   Users must replace the "file-specification" with host computer-specific     
   input file specifications.                                                  
                                                                               
   INPUT contains the SAS statements which assign the variable names and       
   specify the beginning and ending column locations in the LRECL data         
   file for each variable.                                                     
                                                                               
   LABEL assigns variable labels for all variables in the data file.           
   Variable labels and variable names may be identical for some data           
   files.                                                                      
                                                                               
   FORMAT in the SAS data step assigns the formats generated by the            
   PROC FORMAT procedure with the variable values in the SAS system file.      
   When SAS subsequently creates output, it utilizes the labels                
   found in the FORMAT rather than the raw data values.  NOTE: If a format     
   is assigned to a variable with a FORMAT statement, the values for           
   the variable are categorized by their labels *before* compilation and       
   printing by subsequent SAS procedures, i.e., values with identical          
   formats are treated as one group even though their values are               
   different.  Accordingly, users need to look at variable values before       
   jobs are run to assure that inadvertent grouping of results does not        
   occur.                                                                      
                                                                               
   MISSING VALUE RECODE sets user-defined numeric missing values to            
   missing as interpreted by the SAS system.  Only variables with              
   user-defined missing values are included in these statements.               
                                                                               
   Users may combine and modify these sections or parts of these sections      
   to suit their specific needs.  Users will also need to change the           
   file-specification in the INFILE statement to an appropriate filename       
   for their system.  Please note that the PROC FORMAT, FORMAT and             
   MISSING VALUE RECODE sections have been commented out (i.e., '/*').         
   To include the PROC FORMAT, FORMAT and MISSING VALUE RECODE sections        
   in the final SAS setup, remove the comment indicators from those            
   sections.                                                                   
                                                                               
**************************************************************************** */
                                                                               
* SAS DATA, INFILE, INPUT STATEMENTS;                                          
                                                                               
DATA;                                                                          
INFILE "file-specification" LRECL=784;                                         
INPUT                                                                          
   V1 1-3                   V2 4-7                   V3 8-8                    
   V4 9-9                   V5 10-11                 V6 12-13                  
   V7 14-14                 V8 15-15                 V9 16-16                  
   V10 17-18                V11 19-20                V12 21-21                 
   V13 22-22                V14 23-24                V15 25-26                 
   V16 27-27                V17 28-29                V18 30-31                 
   V19 32-32                V20 33-33                V21 34-35                 
   V22 36-36                V23 37-38                V24 39-40                 
   V25 41-41                V26 42-42                V27 43-43                 
   V28 44-44                V29 45-46                V30 47-47                 
   V31 48-48                V32 49-49                V33 50-50                 
   V34 51-54                V35 55-55                V36 56-56                 
   V37 57-57                V38 58-59                V39 60-61                 
   V40 62-62                V41 63-66                V42 67-68                 
   V43 69-70                V44 71-71                V45 72-73                 
   V46 74-74                V47 75-76                V48 77-77                 
   V49 78-79                V50 80-80                V51 81-82                 
   V52 83-84                V53 85-89                V54 90-91                 
   V55 92-95                V56 96-97                V57 $ 98-100              
   V58 101-102              V59 103-104              V60 105-106               
   V61 107-108              V62 109-109              V63 110-110               
   V64 111-111              V65 112-112              V66 113-114               
   V67 115-115              V68 116-116              V69 117-117               
   V70 118-118              V71 119-119              V72 120-120               
   V73 121-121              V74 122-122              V75 123-123               
   V76 124-124              V77 125-125              V78 126-126               
   V79 127-127              V80 128-128              V81 129-129               
   V82 130-130              V83 131-131              V84 132-132               
   V85 133-133              V86 134-135              V87 136-136               
   V88 137-138              V89 139-140              V90 141-142               
   V91 143-144              V92 145-145              V93 146-147               
   V94 148-149              V95 150-151              V96 152-153               
   V97 154-154              V98 155-156              V99 157-158               
   V100 159-160             V101 161-162             V102 163-164              
   V103 165-166             V104 167-168             V105 169-170              
   V106 171-171             V107 172-172             V108 173-174              
   V109 175-176             V110 177-178             V111 179-179              
   V112 180-180             V113 181-181             V114 182-182              
   V115 183-183             V116 184-184             V117 185-185              
   V118 186-187             V119 188-189             V120 190-190              
   V121 191-191             V122 192-195             V123 196-196              
   V124 197-197             V125 198-202             V126 203-203              
   V127 204-204             V128 205-208             V129 209-209              
   V130 210-215             V131 216-217             V132 218-219              
   V133 220-225             V134 226-227             V135 228-229              
   V136 230-231             V137 232-236             V138 237-242              
   V139 243-244             V140 245-250             V141 251-252              
   V142 253-254             V143 255-256             V144 257-258              
   V145 259-260             V146 261-262             V147 263-264              
   V148 265-265             V149 266-267             V150 268-268              
   V151 269-269             V152 270-271             V153 272-273              
   V154 274-274             V155 275-276             V156 277-277              
   V157 278-281             V158 282-283             V159 284-287              
   V160 288-289             V161 290-293             V162 294-295              
   V163 296-299             V164 300-300             V165 301-304              
   V166 305-305             V167 306-309             V168 310-310              
   V169 311-312             V170 313-315             V171 316-316              
   V172 317-318             V173 319-320             V174 321-321              
   V175 322-322             V176 323-324             V177 325-325              
   V178 326-326             V179 327-327             V180 328-328              
   V181 329-332             V182 333-333             V183 334-337              
   V184 338-338             V185 339-342             V186 343-343              
   V187 344-345             V188 346-347             V189 348-349              
   V190 350-351             V191 352-353             V192 354-355              
   V193 356-357             V194 358-359             V195 360-361              
   V196 362-363             V197 364-364             V198 365-365              
   V199 366-366             V200 367-367             V201 368-368              
   V202 369-369             V203 370-373             V204 374-374              
   V205 375-376             V206 377-380             V207 381-384              
   V208 385-388             V209 389-392             V210 393-396              
   V211 397-400             V212 401-402             V213 403-404              
   V214 405-406             V215 407-408             V216 409-410              
   V217 411-411             V218 412-412             V219 413-413              
   V220 414-414             V221 415-417             V222 418-418              
   V223 419-424             V224 425-426             V225 427-431              
   V226 432-436             V227 437-441             V228 442-446              
   V229 447-452             V230 453-457             V231 458-463              
   V232 464-465             V233 466-467             V234 468-469              
   V235 470-471             V236 472-473             V237 474-474              
   V238 475-475             V239 476-476             V240 477-477              
   V241 478-478             V242 479-479             V243 480-480              
   V244 481-481             V245 482-486             V246 487-487              
   V247 488-488             V248 489-489             V249 490-490              
   V250 491-491             V251 492-492             V252 493-493              
   V253 494-494             V254 495-495             V255 496-496              
   V256 497-497             V257 498-498             V258 499-499              
   V259 500-500             V260 501-502             V261 503-504              
   V262 505-505             V263 506-506             V264 507-507              
   V265 508-509             V266 510-511             V267 512-512              
   V268 513-513             V269 514-514             V270 515-515              
   V271 516-516             V272 517-517             V273 518-519              
   V274 520-520             V275 521-522             V276 523-523              
   V277 524-524             V278 525-526             V279 527-528              
   V280 529-529             V281 530-530             V282 531-532              
   V283 533-533             V284 534-535             V285 536-537              
   V286 538-539             V287 540-540             V288 541-541              
   V289 542-542             V290 543-543             V291 544-544              
   V292 545-545             V293 546-546             V294 547-547              
   V295 548-548             V296 549-549             V297 550-550              
   V298 551-551             V299 552-552             V300 553-553              
   V301 554-558             V302 559-559             V303 560-560              
   V304 561-562             V305 563-563             V306 564-564              
   V307 565-570             V308 571-571             V309 572-573              
   V310 574-579             V311 580-581             V312 582-583              
   V313 584-589             V314 590-591             V315 592-597              
   V316 598-599             V317 600-601             V318 602-607              
   V319 608-609             V320 610-611             V321 612-613              
   V322 614-614             V323 615-615             V324 616-616              
   V325 617-618             V326 619-620             V327 621-621              
   V328 622-622             V329 623-623             V330 624-625              
   V331 626-627             V332 628-628             V333 629-630              
   V334 631-632             V335 633-633             V336 634-634              
   V337 635-635             V338 636-637             V339 638-639              
   V340 640-641             V341 642-643             V342 644-645              
   V343 646-646             V344 647-648             V345 649-650              
   V346 651-652             V347 653-654             V348 655-656              
   V349 657-657             V350 658-658             V351 659-659              
   V352 660-660             V353 661-661             V354 662-662              
   V355 663-663             V356 664-664             V357 665-665              
   V358 666-666             V359 667-667             V360 668-668              
   V361 669-669             V362 670-670             V363 671-672              
   V364 673-673             V365 674-674             V366 675-676              
   V367 677-678             V368 679-679             V369 680-680              
   V370 681-681             V371 682-682             V372 683-683              
   V373 684-684             V374 685-685             V375 686-686              
   V376 687-687             V377 688-689             V378 690-690              
   V379 691-691             V380 692-693             V381 694-695              
   V382 696-697             V383 698-699             V384 700-701              
   V385 702-703             V386 704-705             V387 706-706              
   V388 707-708             V389 709-710             V390 711-712              
   V391 713-713             V392 714-715             V393 716-717              
   V394 718-719             V395 720-721             V396 722-722              
   V397 723-728             V398 729-729             V399 730-731              
   V400 732-733             V401 734-735             V402 736-737              
   V403 738-739             V404 740-741             V405 742-743              
   V406 744-745             V407 746-746             V408 747-748              
   V409 749-754             V410 755-760             V411 761-766              
   V412 767-772             V413 773-778             V414 779-784;             
                                                                               
* SAS LABEL STATEMENT;                                                         
                                                                               
LABEL                                                                          
   V1 = "STUDY NUMBER (699)"                                                   
   V2 = "INTERVIEW NUMBER"                                                     
   V3 = "Q.A1 FAM B/W NOW"                                                     
   V4 = "Q.A2 MORE LESS MONEY NOW"                                             
   V5 = "Q.A1-2 B/W"                                                           
   V6 = "Q.A1-2 B/W"                                                           
   V7 = "Q.A3 FINANCIAL EX/UNEX"                                               
   V8 = "Q.A3A IF UNEXPECTED"                                                  
   V9 = "Q.A4 FAMILY INCOME 1960"                                              
   V10 = "Q.A40 B/W  R1"                                                       
   V11 = "Q.A4A B/W  R2"                                                       
   V12 = "Q.A5 INCOME A YEAR NOW"                                              
   V13 = "Q.A6 NORRIES FOR YEAR"                                               
   V14 = "Q.A6A WHAT WORRIES (R1)"                                             
   V15 = "Q.A6A WHAT WORRIES (R2)"                                             
   V16 = "Q.A7 PRICES UP/STABLE"                                               
   V17 = "QA7A REAS PRICE R/F/S R1"                                            
   V18 = "QA7A REAS PRICE R/F/S R2"                                            
   V19 = "QA8 CHAN PRICES G/B"                                                 
   V20 = "QA8A  WHY CHANGE PRICE"                                              
   V21 = "QA9 PRICES 5YR FR NOW"                                               
   V22 = "QA10 BUS COND NEXT YR"                                               
   V23 = "QA10A FACT G/B TIMES(R1)"                                            
   V24 = "QA10A FACT G/B TIMES(R2)"                                            
   V25 = "QA11 BUS B/W LAST YR"                                                
   V26 = "QA12 YR FR NOW B/W"                                                  
   V27 = "Q13 NXT 5YR G/B/WHY"                                                 
   V28 = "QC35 NXT YR G/B BUY AUT"                                             
   V29 = "QC35A WHY"                                                           
   V30 = "QC36 EXP TO BUY AUT"                                                 
   V31 = "QC37 NEW/USED"                                                       
   V32 = "QC38 WHEN BUY"                                                       
   V33 = "QC39 WHAT KIND"                                                      
   V34 = "QC40 HOW MUCH MONEY $"                                               
   V35 = "QC40 HOW MUCH MONEY BKT"                                             
   V36 = "QC41 A YR LATER BUY AUTO"                                            
   V37 = "QD12 NOW G/B BUY HOU GDS"                                            
   V38 = "QD12A WHY  (R1)"                                                     
   V39 = "QD12A WHY (R1)"                                                      
   V40 = "QD20 EXP BUY DUR GDS NTY"                                            
   V41 = "QD23 HOW MUCH MONEY $"                                               
   V42 = "QD23 HOW MUCH MONEY BKT"                                             
   V43 = "QD22 BUY TV NT YR"                                                   
   V44 = "QD23 HOW MUCH $"                                                     
   V45 = "QD22 BUY REFRIG"                                                     
   V46 = "QD23 HOW MUCH $"                                                     
   V47 = "QD22 BUY WASH MACH"                                                  
   V48 = "QD23 HOW MUCH $"                                                     
   V49 = "QD22 BUY FURN"                                                       
   V50 = "QD23 HOW MUCH $ NT YR"                                               
   V51 = "QD21 WHAT OTHER DURABLES"                                            
   V52 = "QUEST FORM"                                                          
   V53 = "SAMPLE BOOK NO"                                                      
   V54 = "SELECTION CODE"                                                      
   V55 = "1960 INTERVIEW NO"                                                   
   V56 = "SPENDING UNIT COMP"                                                  
   V57 = "INTERVIEWER NO"                                                      
   V58 = "INTERVIEWER'S INT NO"                                                
   V59 = "DATE OF INT"                                                         
   V60 = "SEX OF HEAD OF SPEND UN"                                             
   V61 = "AGE FR LISTING BOX"                                                  
   V62 = "AGE BKT"                                                             
   V63 = "IS R HEAD OF SPEND UN"                                               
   V64 = "SEX OF R"                                                            
   V65 = "NO ADULTS IN SPEND UNIT"                                             
   V66 = "WAS HEAD LIV HERE LST YR"                                            
   V67 = "ADULTS NOW NOT IN SU YR"                                             
   V68 = "ADULTS YR AGO NOT PRES"                                              
   V69 = "Q13 NO CH UNDER 18"                                                  
   V70 = "Q13B AGE YOUNGEST CH"                                                
   V71 = "Q13B AGE OLDEST CH"                                                  
   V72 = "NO ADULTS AND CH"                                                    
   V73 = "QK1K2 ATTENDG COLLEGE"                                               
   V74 = "QK3K4 SUP NONE RES COLL"                                             
   V75 = "QK4 DEP OVR 1/2 SP ON SU"                                            
   V76 = "QK5 OTHER DEP"                                                       
   V77 = "QK6 MARRIED/SINGLE/OTH"                                              
   V78 = "QK6A HOW LONG MARRIED"                                               
   V79 = "QK7-K9A EDU HEAD OF SU"                                              
   V80 = "QK10 HEAD BELONG LAB UN"                                             
   V81 = "QK11 HAVE TELE"                                                      
   V82 = "QK12 RACE"                                                           
   V83 = "QK13 LENGTH OF INT"                                                  
   V84 = "QK14 NO OF CALLS"                                                    
   V85 = "QK15 WHO PRES AT INT"                                                
   V86 = "CODER NO"                                                            
   V87 = "OVER 65 IN SU"                                                       
   V88 = "CODES"                                                               
   V89 = "SIZE OF PLACE"                                                       
   V90 = "SMA/NON-SMA"                                                         
   V91 = "COUNTY"                                                              
   V92 = "SAMPLING PROC"                                                       
   V93 = "REGION"                                                              
   V94 = "OCCUP A"                                                             
   V95 = "OCCUP B"                                                             
   V96 = "LIFE CYCLE"                                                          
   V97 = "EXT OF EMPLOY"                                                       
   V98 = "FAM MATCHING IDEN"                                                   
   V99 = "SU INCOME"                                                           
   V100 = "SU INCOME DECILES"                                                  
   V101 = "DISPOSABLE INCOME"                                                  
   V102 = "DISP INCOME DECILES"                                                
   V103 = "HOUSING STATUS AND DUR"                                             
   V104 = "QUINTILE GM"                                                        
   V105 = "LIFE CYCLE GM"                                                      
   V106 = "WI TOTAL INCOME"                                                    
   V107 = "INCOME CHANGE"                                                      
   V108 = "SU TOTAL INCO BR 1959"                                              
   V109 = "QU FORM"                                                            
   V110 = "SU COMP"                                                            
   V111 = "QBB1 OWN/RENT/OTHER HOME"                                           
   V112 = "QBB2 WHEN MOVE TO HOME"                                             
   V113 = "QB1 BUY/BLD REAL ES1960"                                            
   V114 = "QB2 WHAT REAL EST BUY"                                              
   V115 = "QB3 HOW MUCH BRKT"                                                  
   V116 = "QB4 WHAT MO BUY"                                                    
   V117 = "QB5 NOW G/B BUY HOUSE"                                              
   V118 = "QB50 WHY G/B (R1)"                                                  
   V119 = "QB5A WHY G/B (R2)"                                                  
   V120 = "QB6 BUY/BUILD NXT YR"                                               
   V121 = "QB7 COST"                                                           
   V122 = "EXP ON ADD IN 1960 $"                                               
   V123 = "EXP ON ADD IN 1960 BRKT"                                            
   V124 = "EXP ON REPAIRS IN 1960"                                             
   V125 = "TOTAL EXP REP AND ADD 1960"                                         
   V126 = "TOTAL EXP BRKT"                                                     
   V127 = "QB17 EXP NXT YR"                                                    
   V128 = "EXP IN $ NXT YR"                                                    
   V129 = "EXP IN NXT YR BRKT"                                                 
   V130 = "SU INCOME"                                                          
   V131 = "SU INCOME"                                                          
   V132 = "SU INCOME DECILES"                                                  
   V133 = "DISP SU INC"                                                        
   V134 = "DISP SU INC"                                                        
   V135 = "DISP SU INC DECILES"                                                
   V136 = "HOUS STATUS AND DURATION"                                           
   V137 = "SAMPLE BK NO"                                                       
   V138 = "TOTAL FAM INCO FIELD"                                               
   V139 = "TOTAL FAM INCO BRKT"                                                
   V140 = "DISP FAM INC FIELD"                                                 
   V141 = "DISP FAM INC BRKT"                                                  
   V142 = "NO PERSONS IN SU"                                                   
   V143 = "WEIGHTS"                                                            
   V144 = "OWN CAR"                                                            
   V145 = "QC4 CAR NEW/USED"                                                   
   V146 = "QC5 MAKE OF CAR"                                                    
   V147 = "QC5 WHAT YR MODEL"                                                  
   V148 = "QC5C6 WHAT MAKE/YEAR"                                               
   V149 = "QC7 WHEN BOUGHT"                                                    
   V150 = "QC8 WHAT MO"                                                        
   V151 = "QC9 TRADE IN/SELL CAR"                                              
   V152 = "QC10 WHAT MAKE SOLD/TR"                                             
   V153 = "QC10 WHAT MODEL"                                                    
   V154 = "QC10C11 WHAT MAKE"                                                  
   V155 = "QC12 YR BOUGHT"                                                     
   V156 = "QC18-20 FINANC ARR"                                                 
   V157 = "QC17 TOTAL PRICE FI CAR"                                            
   V158 = "QC17 TOT PR BRKT"                                                   
   V159 = "QC18 $ FOR TR/SALE"                                                 
   V160 = "QC18 TR/SALE BRKT $"                                                
   V161 = "NET OUTLAY 1ST CAR"                                                 
   V162 = "NET OUTLAY $ BRKT"                                                  
   V163 = "QC19 PD IN CASH"                                                    
   V164 = "QC19 PD IN CASH BRKT"                                               
   V165 = "QC20 BORROW/FINANCED"                                               
   V166 = "QC20 BORROW/FINANCE BRKT"                                           
   V167 = "QC20 INSTAL DEBT IN $"                                              
   V168 = "QC20 INSTAL DEBT BRKT"                                              
   V169 = "QC20,31 BORROW/OWE"                                                 
   V170 = "QC21 MO PAY"                                                        
   V171 = "QC21 MO PAY IN $ BRKT"                                              
   V172 = "QC22 LENGTH OF DEBT"                                                
   V173 = "QC24 REM  LENGTH OF DEBT"                                           
   V174 = "QC26 ANY REM DEBT"                                                  
   V175 = "$ AMT INST DEBT BRKT"                                               
   V176 = "QC27 TIME PL/BUY CAR"                                               
   V177 = "QC28 CONS PUT OF BUY"                                               
   V178 = "QC29 WHAT PERS TO BUY"                                              
   V179 = "QC30 WHAT CONV TO BUY"                                              
   V180 = "QC13 SELL/SCRAP/6A CAR"                                             
   V181 = "QD1D4 $ TOTAL PRICE"                                                
   V182 = "QD1D4 RANGE TOTAL PRICE"                                            
   V183 = "QD5D6 $ TRADE/INS SALES"                                            
   V184 = "QD5D6 AMT TRADE/INS SALE"                                           
   V185 = "$ TOTAL NET OUTLAY"                                                 
   V186 = "RANGE NET OUTLAY"                                                   
   V187 = "TELEVISION PURCH"                                                   
   V188 = "REFRIG PURCH"                                                       
   V189 = "WASH MACH PURCH"                                                    
   V190 = "STOVE PURCH"                                                        
   V191 = "FURNI PURCH"                                                        
   V192 = "CLOTHES DRY PURCH"                                                  
   V193 = "DISHWASHER PURCH"                                                   
   V194 = "AIR COND PURCH"                                                     
   V195 = "OTHER PURCH R1"                                                     
   V196 = "OTHER PURCH R2"                                                     
   V197 = "QD7 CREDIT OR CASH"                                                 
   V198 = "QD13D14 OTHER LARGE EXP"                                            
   V199 = "QD13D14 OTHER EXP"                                                  
   V200 = "QD13D14 OTH EXP"                                                    
   V201 = "QD13D14 OTH EXP"                                                    
   V202 = "QD15 COST"                                                          
   V203 = "$ MED DEBT LEFT"                                                    
   V204 = "(BKT)MED COST"                                                      
   V205 = "QH43 INC ASSIGNED"                                                  
   V206 = "INSTAL DEBT ON ADD"                                                 
   V207 = "INSTAL DEBT CARS"                                                   
   V208 = "INSTAL DEBT DURABLES"                                               
   V209 = "INSTAL DEBT OTHERS"                                                 
   V210 = "TOTAL INSTAL DEBT"                                                  
   V211 = "ANNUAL PAYM RATE"                                                   
   V212 = "(BRK) INSTAL DEBT REPAIR"                                           
   V213 = "(BRK) INSTAL DEBT CARS"                                             
   V214 = "(BRK) INSTAL DEBT DURAB"                                            
   V215 = "(BRK) INSTAL DEBT OTHER"                                            
   V216 = "(BRK) TOTAL REM INST DE"                                            
   V217 = "(BRK) ANNUAL PAYM RATE"                                             
   V218 = "(BRK) REM DEBT ADD REP"                                             
   V219 = "(BRK) REM DEBT CARS"                                                
   V220 = "(BRK) REM DEBT DURABLE"                                             
   V221 = "RATIO ANN INSTAL DEBT"                                              
   V222 = "(BRK) AIDP/DISP INC"                                                
   V223 = "DISP SU INC"                                                        
   V224 = "AGE SU HEAD"                                                        
   V225 = "SU INCOME"                                                          
   V226 = "LABOR/CAPITAL INCOME"                                               
   V227 = "CAPITAL INC"                                                        
   V228 = "TRANSF PAYM"                                                        
   V229 = "TOTAL SU INCOME"                                                    
   V230 = "TOTAL INC TAX"                                                      
   V231 = "SU DISPOSABLE INC"                                                  
   V232 = "(BRK) TOTAL SU INC"                                                 
   V233 = "INCOME TAX"                                                         
   V234 = "DISP INC"                                                           
   V235 = "H AND W GROSS TAXABLE INC"                                          
   V236 = "OTHERS GROSS TAX INC"                                               
   V237 = "SU TOTAL INC"                                                       
   V238 = "FARMING"                                                            
   V239 = "BOARDERS"                                                           
   V240 = "LABOR/CAPITAL INC"                                                  
   V241 = "RENT"                                                               
   V242 = "INT DIVIDEND TRUST"                                                 
   V243 = "CAPITAL IN SUBTOTAL C"                                              
   V244 = "TRANSF PAYM SUBT D"                                                 
   V245 = "$ HEADS EARNED INC"                                                 
   V246 = "(BRK) HEAD EARN INC"                                                
   V247 = "WIFE EARNED INC"                                                    
   V248 = "WIFE TOTAL INC"                                                     
   V249 = "OTHERS TOTAL INC"                                                   
   V250 = "WIFES NET INC"                                                      
   V251 = "NU MEMBERS $600 MORE INC"                                           
   V252 = "NU GROSS TAX INC $600"                                              
   V253 = "PROP EARN INC WIFE"                                                 
   V254 = "PROP TOTAL INC WIFE"                                                
   V255 = "NU WEEKS WIFE WORKED"                                               
   V256 = "WIFE WORK FULL/PART TIME"                                           
   V257 = "EXPENSES WIFE WORK"                                                 
   V258 = "TYPE INC RECEIV WIFE(R1)"                                           
   V259 = "TYPE INC RECEIV WIFE(R2)"                                           
   V260 = "INC QUINTILES"                                                      
   V261 = "WEIGHTS"                                                            
   V262 = "QG1 EMPLOYED NOW ?"                                                 
   V263 = "QG1A SIMILAR JOBS NOW?"                                             
   V264 = "QG1B HK FEM HD EVER WORK"                                           
   V265 = "QG2 HEAD OCCUP"                                                     
   V266 = "QG3 KIND OF BUSINESS"                                               
   V267 = "QG4 WHO WORK FOR"                                                   
   V268 = "QG5 EMPLOY PEOPLE YOURSF"                                           
   V269 = "QG6 HOW LONG WORK SELF"                                             
   V270 = "QG7 HOW MANY JOBS"                                                  
   V271 = "QG8 TIME PRESENT EMPLOY"                                            
   V272 = "QG9 NU DIFF JOBS SINCE45"                                           
   V273 = "QG101ST FULL TIME JOB"                                              
   V274 = "QG11 WHEN"                                                          
   V275 = "QG12 WHAT EARNED"                                                   
   V276 = "QG13 SATISFACT PROGRESS"                                            
   V277 = "QG1J OTHER WORK"                                                    
   V278 = "QG14A TYPE OTHER WORK"                                              
   V279 = "QG15 AFFECTS ON WORK"                                               
   V280 = "QG16 RESULT ECON WELL-B"                                            
   V281 = "QG17 WHEN"                                                          
   V282 = "QG23 $ MADE 5 YRS AGO"                                              
   V283 = "QG24 FLUCTUATION INC"                                               
   V284 = "REASON R1"                                                          
   V285 = "REASON R2"                                                          
   V286 = "QG26 OTHERS CONTRI INC?"                                            
   V287 = "QG27 WHO?"                                                          
   V288 = "QG28 WHEN?"                                                         
   V289 = "QG29 WAS INC FROM EARN?"                                            
   V290 = "QG30 WHERE MOST INC FROM"                                           
   V291 = "QG31 WIFE WORK FUTURE"                                              
   V292 = "QG32 OTHER STATES"                                                  
   V293 = "QG33 NU REGIONS LIVED"                                              
   V294 = "QG34 UNEMPL/LAID OFF?"                                              
   V295 = "QG35 HOW OFTEN"                                                     
   V296 = "QH1 NU WKS WORK FULLTIME"                                           
   V297 = "QH2 FULL T AND PART T"                                              
   V298 = "QH2 REASONS NOT WORK R1"                                            
   V299 = "QH2 REASONS NOT WORK R2"                                            
   V300 = "QH3 ANY PAYMS/LOANS"                                                
   V301 = "QH6 $ NET FARM INC SU"                                              
   V302 = "QH6 NET FARM INC SU"                                                
   V303 = "QH9 OWN/INT IN BUSINESS"                                            
   V304 = "QH10 WHAT KIND B"                                                   
   V305 = "QH11 SOLE OWNER ?"                                                  
   V306 = "QH12 CORPOR/UNINCORPOR"                                             
   V307 = "QH14 $ LOSS OR PROFIT"                                              
   V308 = "QH14 (BRK)LOSS/PROFIT"                                              
   V309 = "QUESTIONNAIRE A OR B"                                               
   V310 = "$ US SAVINGS BONDS"                                                 
   V311 = "(BRK) US SAV BONDS"                                                 
   V312 = "QJ2 TYPE SAVINGS ACCTS"                                             
   V313 = "$ TOTAL SAV ACCTS"                                                  
   V314 = "(BRK) TOTAL SAV ACCTS"                                              
   V315 = "$ TOTAL CHECK ACCTS"                                                
   V316 = "(BRK) TOTAL CHECK ACCTS"                                            
   V317 = "TYPE LIQ ASSET HOLDINGS"                                            
   V318 = "$ TOTAL LIQ ASSETS"                                                 
   V319 = "(BRK) TOTAL LIQ ASSETS"                                             
   V320 = "ASSIGN REQ:LIQ ASSETS"                                              
   V321 = "ASSIGN COMPON SAV ACCTS"                                            
   V322 = "QJ4 LARGE EXPENSES?"                                                
   V323 = "Q55 WHEN?"                                                          
   V324 = "QJ6 WHAT?"                                                          
   V325 = "QJ7 HOW FINANCL CARE FOR"                                           
   V326 = "QJ8 HANDLE MAJOR MED EXP"                                           
   V327 = "QJ9 EXTRA FUNDS?"                                                   
   V328 = "QJ10 HOW DO YOU FEEL"                                               
   V329 = "QJ11 WHEN HAVE MORE SAV"                                            
   V330 = "QJ12 WHY LESS NOW R1"                                               
   V331 = "QJ12 WHY LESS NOW R2"                                               
   V332 = "QJ13 PLAN LARGE EXPEND"                                             
   V333 = "QJ14 WHAT EXPENDS R1"                                               
   V334 = "QJ14 WHAT EXPENDS R2"                                               
   V335 = "QJ16 AMTS FOR EDUCT"                                                
   V336 = "QJ15 WHEN SPEND"                                                    
   V337 = "QJ17 HAVE MORE FUNDS?"                                              
   V338 = "QJ18 WHEN?"                                                         
   V339 = "QJ19 WHY HAVE LESS NOWR1"                                           
   V340 = "QJ19 WHY LESS NOW R2"                                               
   V341 = "QJ20 MAIN PURPOSE SAV R1"                                           
   V342 = "QJ20 MAIN PURPOS SAV R2"                                            
   V343 = "QJ21 HAVE SAV INCR?"                                                
   V344 = "QJ22 WHAT KIND SAV R1"                                              
   V345 = "QJ22 WHAT KIND SAV R2"                                              
   V346 = "QJ23 WHAT SAV DECRES"                                               
   V347 = "QJ24 HOW SPEND DECRS"                                               
   V348 = "QUESTIONNAIRE A/B"                                                  
   V349 = "QJ25 OWN HOUSE"                                                     
   V350 = "QJ26 WHEN 1ST HOUSE"                                                
   V351 = "QJ27 OWNED MORE THAN 1"                                             
   V352 = "QJ28 HOW VALUE CHANGE"                                              
   V353 = "QJ29 BENEFIT FROM INVEST"                                           
   V354 = "QJ30 INHERITED"                                                     
   V355 = "QJ31 WHEN INHERIT"                                                  
   V356 = "QJ32 INHERIT WORTH"                                                 
   V357 = "QJ33 ANY LARGE GIFTS"                                               
   V358 = "QJ34 WHEN"                                                          
   V359 = "QJ35 WHAT WORTH"                                                    
   V360 = "QJ36 WHERE FAM ASSETS FR"                                           
   V361 = "OCCUP/AGE/SEX OF HEAD"                                              
   V362 = "QJ37 WHAT FUTURE JOBS"                                              
   V363 = "QJ38 WHY JOB CHANGE"                                                
   V364 = "QJ39 WILL EARNINGS CHANG"                                           
   V365 = "QJ40 WHEN GET TOP EARNS"                                            
   V366 = "QJ41 WHAT IS TOP EARNING"                                           
   V367 = "QJ42 HIGH EARN BEFOR RET"                                           
   V368 = "QJ43 WHEN REACH THAT"                                               
   V369 = "QJ44 WHEN RETIRE"                                                   
   V370 = "QJ45 MANAGE FINANCIALLY"                                            
   V371 = "QJ47 SOCIAL SECURITY?"                                              
   V372 = "QJ48 (BRK) SOC SECURITY"                                            
   V373 = "QJ49 OTHER RETIRE FUNDS"                                            
   V374 = "QJ50 (BRK) RETIRE FUNDS"                                            
   V375 = "QJ51 HAVE HOME WH RETIRE"                                           
   V376 = "QJ52 FULLY PAID FOR"                                                
   V377 = "RELUCTANCE TO BE INTERV"                                            
   V378 = "RETIRE/AGE/INC SUMMARY"                                             
   V379 = "RETIRE/OCCUPTION SUMMARY"                                           
   V380 = "TOTAL ASSETS"                                                       
   V381 = "SU INCOME 1959"                                                     
   V382 = "EXTENT EMPLOY"                                                      
   V383 = "VALUE OF ASSETS"                                                    
   V384 = "INCOME DECILES"                                                     
   V385 = "STOCK OWNERSHIP"                                                    
   V386 = "58-59 INCOME CHANGE"                                                
   V387 = "QG11 YR 1ST FULL JOB"                                               
   V388 = "QG18 WAGE IN 1920"                                                  
   V389 = "QG19 WAGE IN 1928"                                                  
   V390 = "QG20 WAGE IN 1940"                                                  
   V391 = "QG21 AFFECT WWII ON WAGE"                                           
   V392 = "QG22 WAGE 1947"                                                     
   V393 = "QG23 WAGE 1955"                                                     
   V394 = "DECILE AT AGE 30"                                                   
   V395 = "HEAD 1960 TOTAL INCOME"                                             
   V396 = "1960 INC COMPARES 1959"                                             
   V397 = "QH45 TOTAL INC 1959"                                                
   V398 = "(BRK)RATIO 60/59 SU INC"                                            
   V399 = "(BRK) DECILES 1920"                                                 
   V400 = "(BRK) DECILES 1928"                                                 
   V401 = "(BRK) DECILES 1940"                                                 
   V402 = "(BRK) DECILES 1947"                                                 
   V403 = "(BRK) DECILES 1955"                                                 
   V404 = "(BRK) DECILES 1960"                                                 
   V405 = "DECILE AGE 40"                                                      
   V406 = "DECILE CHANGE BTW 30-40"                                            
   V407 = "INCOME CHANGE"                                                      
   V408 = "SU TOT INC BRK 1959"                                                
   V409 = "R'S INCOME 1920"                                                    
   V410 = "R'S INC 1928"                                                       
   V411 = "R'S INC 1940"                                                       
   V412 = "R'S INC 1947"                                                       
   V413 = "R'S INC 1955"                                                       
   V414 = "R'S INC 1960";                                                      
                                                                               
* USER-DEFINED MISSING VALUE RECODE TO SAS SYSMIS;                             
                                                                               
/*                                                                             
   IF V1 LE -000009 THEN V1=.;         IF V2 LE -000009 THEN V2=.;             
   IF V3 GE 0000008 THEN V3=.;         IF V4 GE 0000009 THEN V4=.;             
   IF V5 LE -000009 OR V5=0000000 THEN V5=.;                                   
   IF V6 LE -000009 OR V6=0000000 THEN V6=.;                                   
   IF V7 GE 0000009 THEN V7=.;                                                 
   IF V8 GE 0000009 OR V8=0000000 THEN V8=.;                                   
   IF V9 GE 0000009 THEN V9=.;                                                 
   IF V10 LE -000009 OR V10=0000000 THEN V10=.;                                
   IF V11 LE -000009 OR V11=0000000 THEN V11=.;                                
   IF V12 GE 0000008 THEN V12=.;       IF V13 GE 0000009 THEN V13=.;           
   IF V14 GE 0000099 OR V14=0000000 THEN V14=.;                                
   IF V15 GE 0000099 OR V15=0000000 THEN V15=.;                                
   IF V16 GE 0000008 THEN V16=.;                                               
   IF V17 GE 0000099 OR V17=0000000 THEN V17=.;                                
   IF V18 GE 0000099 OR V18=0000000 THEN V18=.;                                
   IF V19 GE 0000009 OR V19=0000000 THEN V19=.;                                
   IF V20 GE 0000009 OR V20=0000000 THEN V20=.;                                
   IF V21 GE 0000011 OR V21=0000000 THEN V21=.;                                
   IF V22 GE 0000008 THEN V22=.;                                               
   IF V23 GE 0000098 OR V23=0000000 THEN V23=.;                                
   IF V24 GE 0000098 OR V24=0000000 THEN V24=.;                                
   IF V25 GE 0000008 THEN V25=.;       IF V26 GE 0000008 THEN V26=.;           
   IF V27 GE 0000009 THEN V27=.;       IF V28 GE 0000008 THEN V28=.;           
   IF V29 GE 0000099 OR V29=0000000 THEN V29=.;                                
   IF V30 GE 0000009 THEN V30=.;                                               
   IF V31 GE 0000009 OR V31=0000000 THEN V31=.;                                
   IF V32 GE 0000009 OR V32=0000000 THEN V32=.;                                
   IF V33 GE 0000009 OR V33=0000000 THEN V33=.;                                
   IF V34 LE -000999 OR V34=0000000 THEN V34=.;                                
   IF V35 GE 0000009 OR V35=0000000 THEN V35=.;                                
   IF V36 GE 0000009 OR V36=0000000 THEN V36=.;                                
   IF V37 GE 0000008 THEN V37=.;                                               
   IF V38 GE 0000099 OR V38=0000000 THEN V38=.;                                
   IF V39 GE 0000099 OR V39=0000000 THEN V39=.;                                
   IF V40 GE 0000009 THEN V40=.;                                               
   IF V41 LE -000999 OR V41=0000000 THEN V41=.;                                
   IF V42 GE 0000009 OR V42=0000000 THEN V42=.;                                
   IF V43 LE -000009 OR V43=0000000 THEN V43=.;                                
   IF V44 GE 0000009 OR V44=0000000 THEN V44=.;                                
   IF V45 LE -000009 OR V45=0000000 THEN V45=.;                                
   IF V46 GE 0000009 OR V46=0000000 THEN V46=.;                                
   IF V47 LE -000009 OR V47=0000000 THEN V47=.;                                
   IF V48 GE 0000009 OR V48=0000000 THEN V48=.;                                
   IF V49 LE -000009 OR V49=0000000 THEN V49=.;                                
   IF V50 GE 0000009 OR V50=0000000 THEN V50=.;                                
   IF V51 LE -000009 OR V51=0000000 THEN V51=.;                                
   IF V52 LE -000009 THEN V52=.;       IF V54 LE -000009 THEN V54=.;           
   IF V55 LE -000009 THEN V55=.;       IF V56 GE 0000099 THEN V56=.;           
   IF V58 GE 0000099 THEN V58=.;       IF V59 GE 0000009 THEN V59=.;           
   IF V60 LE -000009 THEN V60=.;       IF V61 GE 0000099 THEN V61=.;           
   IF V62 GE 0000009 THEN V62=.;       IF V63 GE 0000009 THEN V63=.;           
   IF V64 GE 0000009 THEN V64=.;       IF V65 GE 0000009 THEN V65=.;           
   IF V66 LE -000009 THEN V66=.;       IF V67 GE 0000009 THEN V67=.;           
   IF V68 GE 0000009 OR V68=0000000 THEN V68=.;                                
   IF V69 GE 0000009 OR V69=0000000 THEN V69=.;                                
   IF V70 GE 0000009 OR V70=0000000 THEN V70=.;                                
   IF V71 GE 0000009 OR V71=0000000 THEN V71=.;                                
   IF V72 GE 0000009 THEN V72=.;       IF V73 GE 0000009 THEN V73=.;           
   IF V74 GE 0000009 THEN V74=.;                                               
   IF V75 GE 0000009 OR V75=0000000 THEN V75=.;                                
   IF V76 GE 0000009 THEN V76=.;       IF V77 GE 0000009 THEN V77=.;           
   IF V78 GE 0000009 OR V78=0000000 THEN V78=.;                                
   IF V79 GE 0000009 THEN V79=.;       IF V80 GE 0000009 THEN V80=.;           
   IF V81 GE 0000009 THEN V81=.;       IF V82 GE 0000009 THEN V82=.;           
   IF V83 GE 0000009 THEN V83=.;       IF V84 GE 0000009 THEN V84=.;           
   IF V85 GE 0000009 THEN V85=.;       IF V86 LE -000009 THEN V86=.;           
   IF V87 GE 0000009 THEN V87=.;       IF V88 LE -000009 THEN V88=.;           
   IF V89 LE -000009 THEN V89=.;       IF V90 LE -000009 THEN V90=.;           
   IF V91 LE -000009 THEN V91=.;       IF V92 GE 0000009 THEN V92=.;           
   IF V93 LE -000009 THEN V93=.;       IF V94 LE -000009 THEN V94=.;           
   IF V95 LE -000009 THEN V95=.;       IF V96 LE -000009 THEN V96=.;           
   IF V97 GE 0000009 OR V97=0000000 THEN V97=.;                                
   IF V98 LE -000009 OR V98=0000000 THEN V98=.;                                
   IF V99 LE -000009 THEN V99=.;       IF V100 LE -000009 THEN V100=.;         
   IF V101 LE -000009 THEN V101=.;     IF V102 LE -000009 THEN V102=.;         
   IF V103 LE -000009 THEN V103=.;     IF V104 LE -000009 THEN V104=.;         
   IF V105 LE -000009 THEN V105=.;     IF V106 GE 0000009 THEN V106=.;         
   IF V107 GE 0000009 THEN V107=.;     IF V108 GE 0000011 THEN V108=.;         
   IF V109 LE -000009 THEN V109=.;     IF V110 LE -000009 THEN V110=.;         
   IF V111 GE 0000009 OR V111=0000000 THEN V111=.;                             
   IF V112 GE 0000009 OR V112=0000000 THEN V112=.;                             
   IF V113 GE 0000009 OR V113=0000000 THEN V113=.;                             
   IF V114 GE 0000009 OR V114=0000000 THEN V114=.;                             
   IF V115 GE 0000009 OR V115=0000000 THEN V115=.;                             
   IF V116 GE 0000009 OR V116=0000000 THEN V116=.;                             
   IF V117 GE 0000008 THEN V117=.;                                             
   IF V118 GE 0000099 OR V118=0000000 THEN V118=.;                             
   IF V119 GE 0000099 OR V119=0000000 THEN V119=.;                             
   IF V120 GE 0000009 THEN V120=.;                                             
   IF V121 GE 0000009 OR V121=0000000 THEN V121=.;                             
   IF V122 LE -000999 OR V122=0000000 THEN V122=.;                             
   IF V123 GE 0000009 OR V123=0000000 THEN V123=.;                             
   IF V124 GE 0000009 OR V124=0000000 THEN V124=.;                             
   IF V125 LE -009999 OR V125=0000000 THEN V125=.;                             
   IF V126 GE 0000009 OR V126=0000000 THEN V126=.;                             
   IF V127 GE 0000009 THEN V127=.;                                             
   IF V128 GE 0009999 OR V128=0000000 THEN V128=.;                             
   IF V129 GE 0000009 OR V129=0000000 THEN V129=.;                             
   IF V130=0000000 THEN V130=.;        IF V131 GE 0000099 THEN V131=.;         
   IF V132 LE -000009 THEN V132=.;     IF V133=0000000 THEN V133=.;            
   IF V134 LE -000009 THEN V134=.;     IF V135 LE -000009 THEN V135=.;         
   IF V136 LE -000009 THEN V136=.;     IF V137 LE -000009 THEN V137=.;         
   IF V138=0000000 THEN V138=.;        IF V139 LE -000009 THEN V139=.;         
   IF V140=0000000 THEN V140=.;        IF V141 LE -000009 THEN V141=.;         
   IF V142 LE -000009 THEN V142=.;     IF V143 LE -000009 THEN V143=.;         
   IF V144 LE -000009 THEN V144=.;                                             
   IF V145 LE -000009 OR V145=0000000 THEN V145=.;                             
   IF V146 GE 0000099 OR V146=0000000 THEN V146=.;                             
   IF V147 GE 0000099 OR V147=0000000 THEN V147=.;                             
   IF V148 GE 0000009 OR V148=0000000 THEN V148=.;                             
   IF V149 GE 0000099 OR V149=0000000 THEN V149=.;                             
   IF V150 GE 0000009 OR V150=0000000 THEN V150=.;                             
   IF V151 GE 0000009 OR V151=0000000 THEN V151=.;                             
   IF V152 GE 0000099 OR V152=0000000 THEN V152=.;                             
   IF V153 GE 0000099 OR V153=0000000 THEN V153=.;                             
   IF V154 GE 0000009 OR V154=0000000 THEN V154=.;                             
   IF V155 GE 0000099 OR V155=0000000 THEN V155=.;                             
   IF V156 GE 0000009 OR V156=0000000 THEN V156=.;                             
   IF V157=0000000 THEN V157=.;                                                
   IF V158 LE -000009 OR V158=0000000 THEN V158=.;                             
   IF V159=0000000 THEN V159=.;                                                
   IF V160 LE -000009 OR V160=0000000 THEN V160=.;                             
   IF V161=0000000 THEN V161=.;                                                
   IF V162 LE -000009 OR V162=0000000 THEN V162=.;                             
   IF V163=0000000 THEN V163=.;                                                
   IF V164 GE 0000009 OR V164=0000000 THEN V164=.;                             
   IF V165 LE -000999 OR V165=0000000 THEN V165=.;                             
   IF V166 GE 0000009 OR V166=0000000 THEN V166=.;                             
   IF V167 LE -000999 OR V167=0000000 THEN V167=.;                             
   IF V168 GE 0000009 OR V168=0000000 THEN V168=.;                             
   IF V169 LE -000009 OR V169=0000000 THEN V169=.;                             
   IF V170 LE -000099 OR V170=0000000 THEN V170=.;                             
   IF V171 GE 0000009 OR V171=0000000 THEN V171=.;                             
   IF V172 GE 0000099 OR V172=0000000 THEN V172=.;                             
   IF V173 GE 0000099 OR V173=0000000 THEN V173=.;                             
   IF V174 GE 0000009 OR V174=0000000 THEN V174=.;                             
   IF V175 GE 0000009 OR V175=0000000 THEN V175=.;                             
   IF V176 GE 0000099 OR V176=0000000 THEN V176=.;                             
   IF V177 GE 0000009 OR V177=0000000 THEN V177=.;                             
   IF V178 GE 0000009 OR V178=0000000 THEN V178=.;                             
   IF V179 GE 0000009 OR V179=0000000 THEN V179=.;                             
   IF V180 GE 0000009 THEN V180=.;                                             
   IF V181 LE -000999 OR V181=0000000 THEN V181=.;                             
   IF V182 GE 0000009 OR V182=0000000 THEN V182=.;                             
   IF V183 LE -000999 OR V183=0000000 THEN V183=.;                             
   IF V184 GE 0000009 OR V184=0000000 THEN V184=.;                             
   IF V185 LE -000999 OR V185=0000000 THEN V185=.;                             
   IF V186 GE 0000009 OR V186=0000000 THEN V186=.;                             
   IF V187 LE -000009 OR V187=0000000 THEN V187=.;                             
   IF V188 LE -000009 OR V188=0000000 THEN V188=.;                             
   IF V189 LE -000009 OR V189=0000000 THEN V189=.;                             
   IF V190 LE -000009 OR V190=0000000 THEN V190=.;                             
   IF V191 LE -000009 OR V191=0000000 THEN V191=.;                             
   IF V192 LE -000009 OR V192=0000000 THEN V192=.;                             
   IF V193 LE -000009 OR V193=0000000 THEN V193=.;                             
   IF V194 LE -000009 OR V194=0000000 THEN V194=.;                             
   IF V195 LE -000009 OR V195=0000000 THEN V195=.;                             
   IF V196 LE -000009 OR V196=0000000 THEN V196=.;                             
   IF V197 GE 0000009 OR V197=0000000 THEN V197=.;                             
   IF V198 GE 0000009 OR V198=0000000 THEN V198=.;                             
   IF V199 GE 0000009 OR V199=0000000 THEN V199=.;                             
   IF V200 GE 0000009 OR V200=0000000 THEN V200=.;                             
   IF V201 GE 0000009 OR V201=0000000 THEN V201=.;                             
   IF V202 GE 0000009 OR V202=0000000 THEN V202=.;                             
   IF V203 LE -000999 OR V203=0000000 THEN V203=.;                             
   IF V204 GE 0000009 OR V204=0000000 THEN V204=.;                             
   IF V205 LE -000009 THEN V205=.;     IF V206=0000000 THEN V206=.;            
   IF V207=0000000 THEN V207=.;        IF V208=0000000 THEN V208=.;            
   IF V209=0000000 THEN V209=.;        IF V210=0000000 THEN V210=.;            
   IF V211 LE -000999 OR V211=0000000 THEN V211=.;                             
   IF V212 LE -000009 OR V212=0000000 THEN V212=.;                             
   IF V213 LE -000009 OR V213=0000000 THEN V213=.;                             
   IF V214 LE -000009 OR V214=0000000 THEN V214=.;                             
   IF V215 LE -000009 OR V215=0000000 THEN V215=.;                             
   IF V216 LE -000009 OR V216=0000000 THEN V216=.;                             
   IF V217 GE 0000009 OR V217=0000000 THEN V217=.;                             
   IF V218 GE 0000009 OR V218=0000000 THEN V218=.;                             
   IF V219 GE 0000009 OR V219=0000000 THEN V219=.;                             
   IF V220 GE 0000009 OR V220=0000000 THEN V220=.;                             
   IF V221 GE 0000999 OR V221=0000000 THEN V221=.;                             
   IF V222 GE 0000009 OR V222=0000000 THEN V222=.;                             
   IF V223=0000000 THEN V223=.;        IF V224 GE 0000011 THEN V224=.;         
   IF V225 LE -009999 OR V225=0000000 THEN V225=.;                             
   IF V226 LE -009999 OR V226=0000000 THEN V226=.;                             
   IF V227 LE -009999 OR V227=0000000 THEN V227=.;                             
   IF V228 LE -009999 OR V228=0000000 THEN V228=.;                             
   IF V229=0000000 THEN V229=.;        IF V230=0000000 THEN V230=.;            
   IF V231=0000000 THEN V231=.;        IF V232 LE -000009 THEN V232=.;         
   IF V233 LE -000009 THEN V233=.;     IF V234 LE -000009 THEN V234=.;         
   IF V235 LE -000009 THEN V235=.;     IF V236 LE -000009 THEN V236=.;         
   IF V237 GE 0000009 THEN V237=.;     IF V238 GE 0000009 THEN V238=.;         
   IF V239 GE 0000009 THEN V239=.;     IF V240 GE 0000009 THEN V240=.;         
   IF V241 GE 0000009 THEN V241=.;     IF V242 GE 0000009 THEN V242=.;         
   IF V243 GE 0000009 THEN V243=.;     IF V244 GE 0000009 THEN V244=.;         
   IF V245 LE -009999 OR V245=0000000 THEN V245=.;                             
   IF V246 GE 0000009 THEN V246=.;     IF V247 GE 0000009 THEN V247=.;         
   IF V248 GE 0000009 THEN V248=.;     IF V249 GE 0000009 THEN V249=.;         
   IF V250 GE 0000009 THEN V250=.;     IF V251 GE 0000009 THEN V251=.;         
   IF V252 GE 0000009 THEN V252=.;     IF V253 GE 0000008 THEN V253=.;         
   IF V254 GE 0000008 THEN V254=.;     IF V255 GE 0000008 THEN V255=.;         
   IF V256 GE 0000008 THEN V256=.;     IF V257 GE 0000008 THEN V257=.;         
   IF V258 GE 0000009 OR V258=0000000 THEN V258=.;                             
   IF V259 GE 0000009 OR V259=0000000 THEN V259=.;                             
   IF V260 LE -000009 THEN V260=.;     IF V261 LE -000009 THEN V261=.;         
   IF V262 GE 0000009 THEN V262=.;                                             
   IF V263 GE 0000009 OR V263=0000000 THEN V263=.;                             
   IF V264 GE 0000009 OR V264=0000000 THEN V264=.;                             
   IF V265 GE 0000099 THEN V265=.;                                             
   IF V266 GE 0000099 OR V266=0000000 THEN V266=.;                             
   IF V267 GE 0000009 OR V267=0000000 THEN V267=.;                             
   IF V268 GE 0000009 OR V268=0000000 THEN V268=.;                             
   IF V269 GE 0000009 OR V269=0000000 THEN V269=.;                             
   IF V270 GE 0000009 OR V270=0000000 THEN V270=.;                             
   IF V271 GE 0000009 OR V271=0000000 THEN V271=.;                             
   IF V272 GE 0000009 OR V272=0000000 THEN V272=.;                             
   IF V273 LE -000009 OR V273=0000000 THEN V273=.;                             
   IF V274 GE 0000009 OR V274=0000000 THEN V274=.;                             
   IF V275 GE 0000011 THEN V275=.;                                             
   IF V276 GE 0000009 OR V276=0000000 THEN V276=.;                             
   IF V277 GE 0000009 OR V277=0000000 THEN V277=.;                             
   IF V278 GE 0000011 OR V278=0000000 THEN V278=.;                             
   IF V279 GE 0000011 OR V279=0000000 THEN V279=.;                             
   IF V280 GE 0000009 OR V280=0000000 THEN V280=.;                             
   IF V281 GE 0000009 OR V281=0000000 THEN V281=.;                             
   IF V282 GE 0000011 THEN V282=.;                                             
   IF V283 GE 0000009 OR V283=0000000 THEN V283=.;                             
   IF V284 GE 0000099 OR V284=0000000 THEN V284=.;                             
   IF V285 GE 0000099 OR V285=0000000 THEN V285=.;                             
   IF V286 GE 0000009 OR V286=0000000 THEN V286=.;                             
   IF V287 GE 0000009 OR V287=0000000 THEN V287=.;                             
   IF V288 GE 0000009 OR V288=0000000 THEN V288=.;                             
   IF V289 GE 0000009 OR V289=0000000 THEN V289=.;                             
   IF V290 GE 0000009 OR V290=0000000 THEN V290=.;                             
   IF V291 GE 0000009 OR V291=0000000 THEN V291=.;                             
   IF V292 GE 0000009 OR V292=0000000 THEN V292=.;                             
   IF V293 GE 0000009 OR V293=0000000 THEN V293=.;                             
   IF V294 GE 0000009 OR V294=0000000 THEN V294=.;                             
   IF V295 GE 0000009 OR V295=0000000 THEN V295=.;                             
   IF V296 GE 0000008 OR V296=0000000 THEN V296=.;                             
   IF V297 GE 0000008 OR V297=0000000 THEN V297=.;                             
   IF V298 GE 0000009 OR V298=0000000 THEN V298=.;                             
   IF V299 GE 0000009 OR V299=0000000 THEN V299=.;                             
   IF V300 GE 0000009 OR V300=0000000 THEN V300=.;                             
   IF V301 LE -009999 OR V301=0000000 THEN V301=.;                             
   IF V302 GE 0000009 OR V302=0000000 THEN V302=.;                             
   IF V303 GE 0000009 THEN V303=.;                                             
   IF V304 LE -000009 OR V304=0000000 THEN V304=.;                             
   IF V305 GE 0000009 OR V305=0000000 THEN V305=.;                             
   IF V306 GE 0000009 OR V306=0000000 THEN V306=.;                             
   IF V307 LE -099999 OR V307=0000000 THEN V307=.;                             
   IF V308 GE 0000009 THEN V308=.;     IF V309 LE -000009 THEN V309=.;         
   IF V310=0000000 THEN V310=.;                                                
   IF V311 LE -000009 OR V311=0000000 THEN V311=.;                             
   IF V312 LE -000009 OR V312=0000000 THEN V312=.;                             
   IF V313=0000000 THEN V313=.;                                                
   IF V314 LE -000009 OR V314=0000000 THEN V314=.;                             
   IF V315=0000000 THEN V315=.;                                                
   IF V316 LE -000009 OR V316=0000000 THEN V316=.;                             
   IF V317 LE -000009 OR V317=0000000 THEN V317=.;                             
   IF V318=0000000 THEN V318=.;                                                
   IF V319 LE -000009 OR V319=0000000 THEN V319=.;                             
   IF V320 LE -000009 OR V320=0000000 THEN V320=.;                             
   IF V321 LE -000009 OR V321=0000000 THEN V321=.;                             
   IF V322 GE 0000009 OR V322=0000000 THEN V322=.;                             
   IF V323 GE 0000009 OR V323=0000000 THEN V323=.;                             
   IF V324 GE 0000009 OR V324=0000000 THEN V324=.;                             
   IF V325 GE 0000010 OR V325=0000000 THEN V325=.;                             
   IF V326 GE 0000010 OR V326=0000000 THEN V326=.;                             
   IF V327 GE 0000009 THEN V327=.;                                             
   IF V328 GE 0000009 OR V328=0000000 THEN V328=.;                             
   IF V329 GE 0000009 OR V329=0000000 THEN V329=.;                             
   IF V330 GE 0000099 OR V330=0000000 THEN V330=.;                             
   IF V331 GE 0000011 OR V331=0000000 THEN V331=.;                             
   IF V332 GE 0000009 OR V332=0000000 THEN V332=.;                             
   IF V333 GE 0000011 OR V333=0000000 THEN V333=.;                             
   IF V334 GE 0000011 OR V334=0000000 THEN V334=.;                             
   IF V335 GE 0000009 OR V335=0000000 THEN V335=.;                             
   IF V336 GE 0000009 OR V336=0000000 THEN V336=.;                             
   IF V337 GE 0000009 OR V337=0000000 THEN V337=.;                             
   IF V338 GE 0000010 OR V338=0000000 THEN V338=.;                             
   IF V339 GE 0000011 OR V339=0000000 THEN V339=.;                             
   IF V340 GE 0000011 OR V340=0000000 THEN V340=.;                             
   IF V341 GE 0000011 OR V341=0000000 THEN V341=.;                             
   IF V342 GE 0000011 OR V342=0000000 THEN V342=.;                             
   IF V343 GE 0000009 OR V343=0000000 THEN V343=.;                             
   IF V344 GE 0000009 OR V344=0000000 THEN V344=.;                             
   IF V345 GE 0000009 OR V345=0000000 THEN V345=.;                             
   IF V346 GE 0000009 OR V346=0000000 THEN V346=.;                             
   IF V347 GE 0000011 OR V347=0000000 THEN V347=.;                             
   IF V348 LE -000009 THEN V348=.;                                             
   IF V349 GE 0000009 OR V349=0000000 THEN V349=.;                             
   IF V350 GE 0000009 OR V350=0000000 THEN V350=.;                             
   IF V351 GE 0000009 OR V351=0000000 THEN V351=.;                             
   IF V352 GE 0000009 OR V352=0000000 THEN V352=.;                             
   IF V353 GE 0000009 OR V353=0000000 THEN V353=.;                             
   IF V354 GE 0000009 OR V354=0000000 THEN V354=.;                             
   IF V355 GE 0000009 OR V355=0000000 THEN V355=.;                             
   IF V356 GE 0000009 OR V356=0000000 THEN V356=.;                             
   IF V357 GE 0000009 OR V357=0000000 THEN V357=.;                             
   IF V358 GE 0000009 OR V358=0000000 THEN V358=.;                             
   IF V359 GE 0000009 OR V359=0000000 THEN V359=.;                             
   IF V360 GE 0000009 OR V360=0000000 THEN V360=.;                             
   IF V361 GE 0000009 THEN V361=.;                                             
   IF V362 GE 0000009 OR V362=0000000 THEN V362=.;                             
   IF V363 GE 0000011 OR V363=0000000 THEN V363=.;                             
   IF V364 GE 0000009 OR V364=0000000 THEN V364=.;                             
   IF V365 GE 0000009 OR V365=0000000 THEN V365=.;                             
   IF V366 GE 0000010 THEN V366=.;     IF V367 GE 0000010 THEN V367=.;         
   IF V368 GE 0000009 OR V368=0000000 THEN V368=.;                             
   IF V369 GE 0000009 OR V369=0000000 THEN V369=.;                             
   IF V370 GE 0000009 OR V370=0000000 THEN V370=.;                             
   IF V371 GE 0000009 OR V371=0000000 THEN V371=.;                             
   IF V372 GE 0000009 OR V372=0000000 THEN V372=.;                             
   IF V373 GE 0000009 OR V373=0000000 THEN V373=.;                             
   IF V374 GE 0000009 OR V374=0000000 THEN V374=.;                             
   IF V375 GE 0000009 OR V375=0000000 THEN V375=.;                             
   IF V376 GE 0000009 OR V376=0000000 THEN V376=.;                             
   IF V377 LE -000009 THEN V377=.;     IF V378 GE 0000009 THEN V378=.;         
   IF V379 GE 0000009 THEN V379=.;                                             
   IF V380 LE -000009 OR V380=0000099 THEN V380=.;                             
   IF V381 GE 0000011 THEN V381=.;     IF V382 LE -000009 THEN V382=.;         
   IF V383 LE -000009 OR V383=0000009 THEN V383=.;                             
   IF V384 LE -000009 THEN V384=.;     IF V385 LE -000009 THEN V385=.;         
   IF V386 LE -000009 OR V386=0000009 THEN V386=.;                             
   IF V387 GE 0000009 OR V387=0000000 THEN V387=.;                             
   IF V388 GE 0000010 THEN V388=.;     IF V389 GE 0000010 THEN V389=.;         
   IF V390 GE 0000010 THEN V390=.;                                             
   IF V391 GE 0000009 OR V391=0000000 THEN V391=.;                             
   IF V392 GE 0000010 THEN V392=.;     IF V393 GE 0000010 THEN V393=.;         
   IF V394 GE 0000011 OR V394=0000000 THEN V394=.;                             
   IF V395 GE 0000010 THEN V395=.;     IF V396 GE 0000009 THEN V396=.;         
   IF V397 LE -099999 OR V397=0000000 THEN V397=.;                             
   IF V398 GE 0000009 THEN V398=.;                                             
   IF V399 GE 0000011 OR V399=0000000 THEN V399=.;                             
   IF V400 GE 0000011 OR V400=0000000 THEN V400=.;                             
   IF V401 GE 0000011 OR V401=0000000 THEN V401=.;                             
   IF V402 GE 0000011 OR V402=0000000 THEN V402=.;                             
   IF V403 GE 0000011 OR V403=0000000 THEN V403=.;                             
   IF V404 GE 0000011 OR V404=0000000 THEN V404=.;                             
   IF V405 GE 0000011 OR V405=0000000 THEN V405=.;                             
   IF V406 LE -000009 OR V406=0000000 THEN V406=.;                             
   IF V407 GE 0000009 THEN V407=.;     IF V408 GE 0000010 THEN V408=.;         
   IF V409 LE -099999 OR V409=0000000 THEN V409=.;                             
   IF V410 LE -099999 OR V410=0000000 THEN V410=.;                             
   IF V411 LE -099999 OR V411=0000000 THEN V411=.;                             
   IF V412 LE -099999 OR V412=0000000 THEN V412=.;                             
   IF V413 LE -099999 OR V413=0000000 THEN V413=.;                             
   IF V414 LE -099999 OR V414=0000000 THEN V414=.;                             
                                                                               
*/                                                                             
