/*                                                                             
               SAS DATA DEFINITION STATEMENTS FOR ICPSR 3600                   
                     SURVEY OF CONSUMER FINANCES, 1955                         
                            MARCH 1974 VERSION                                 
                                                                               
   The following SAS setup sections may appear in this file for the LRECL      
   version of this data collection.  These sections are listed below:          
                                                                               
   PROC FORMAT, in these statements, creates user-defined labels as            
   formats for variable values.   Formats replace original values with the     
   user-defined labels in subsequent SAS procedures once the formats           
   are assigned to a variable by the FORMAT command in the DATA step.          
   Not all variables necessarily have user-defined formats.                    
                                                                               
   DATA begins a SAS data step and names an output SAS dataset.                
                                                                               
   INFILE identifies the input file to be read with the input statement.       
   Users must replace the "file-specification" with host computer-specific     
   input file specifications.                                                  
                                                                               
   INPUT contains the SAS statements which assign the variable names and       
   specify the beginning and ending column locations in the LRECL data         
   file for each variable.                                                     
                                                                               
   LABEL assigns variable labels for all variables in the data file.           
   Variable labels and variable names may be identical for some data           
   files.                                                                      
                                                                               
   FORMAT in the SAS data step assigns the formats generated by the            
   PROC FORMAT procedure with the variable values in the SAS system file.      
   When SAS subsequently creates output, it utilizes the labels                
   found in the FORMAT rather than the raw data values.  NOTE: If a format     
   is assigned to a variable with a FORMAT statement, the values for           
   the variable are categorized by their labels *before* compilation and       
   printing by subsequent SAS procedures, i.e., values with identical          
   formats are treated as one group even though their values are               
   different.  Accordingly, users need to look at variable values before       
   jobs are run to assure that inadvertent grouping of results does not        
   occur.                                                                      
                                                                               
   MISSING VALUE RECODE sets user-defined numeric missing values to            
   missing as interpreted by the SAS system.  Only variables with              
   user-defined missing values are included in these statements.               
                                                                               
   Users may combine and modify these sections or parts of these sections      
   to suit their specific needs.  Users will also need to change the           
   file-specification in the INFILE statement to an appropriate filename       
   for their system.  Please note that the PROC FORMAT, FORMAT and             
   MISSING VALUE RECODE sections have been commented out (i.e., '/*').         
   To include the PROC FORMAT, FORMAT and MISSING VALUE RECODE sections        
   in the final SAS setup, remove the comment indicators from those            
   sections.                                                                   
                                                                               
**************************************************************************** */
                                                                               
* SAS DATA, INFILE, INPUT STATEMENTS;                                          
                                                                               
DATA;                                                                          
INFILE "file-specification" LRECL=681;                                         
INPUT                                                                          
   V1 1-4                   V2 5-8                   V3 9-10                   
   V4 11-14                 V5 15-15                 V6 16-16                  
   V7 17-17                 V8 18-18                 V9 19-19                  
   V10 20-20                V11 21-21                V12 22-22                 
   V13 23-25                V14 26-27                V15 28-28                 
   V16 29-29                V17 30-30                V18 31-32                 
   V19 33-34                V20 35-35                V21 36-36                 
   V22 37-37                V23 38-38                V24A 39-40                
   V24B 41-42               V24C 43-44               V25 45-45                 
   V26A 46-47               V26B 48-49               V27 50-50                 
   V28A 51-52               V28B 53-54               V29 55-56                 
   V30 57-58                V31 59-59                V32 60-61                 
   V33 62-63                V34 64-64                V35 65-66                 
   V36 67-68                V37 69-71                V38 72-73                 
   V39 74-74                V40 75-75                V41 76-80                 
   V42 81-81                V43 82-82                V44 83-83                 
   V45 84-84                V46 85-89                V47 90-92                 
   V48 93-93                V49 94-94                V50 95-96                 
   V51A 97-98               V51B 99-100              V52 101-101               
   V53 102-102              V54 103-103              V55 104-104               
   V56A 105-105             V56B 106-106             V57 107-107               
   V58 108-109              V59 110-110              V60A 111-112              
   V60B 113-114             V61 115-115              V62 116-117               
   V63 118-118              V64 119-119              V65A 120-121              
   V65B 122-123             V66A 124-125             V66B 126-127              
   V67 128-128              V68 129-129              V69 130-133               
   V70 134-134              V71 135-138              V72 139-139               
   V73 140-140              V74 141-141              V75 142-143               
   V76 144-144              V77 145-147              V78 148-148               
   V79 149-149              V80 150-150              V81 151-152               
   V82 153-153              V83 154-154              V84 155-155               
   V85 156-157              V86 158-158              V87 159-159               
   V88 160-160	            V89 161-162              V90 163-164                
   V91 165-166              V92 167-167              V93 168-171               
   V94 172-172              V95 173-176              V96 177-178               
   V97 179-180              V98 181-181              V99 182-182               
   V100 183-183             V101 184-187             V102 188-188              
   V103 189-189             V104 190-191             V105 192-193              
   V106 194-194             V107 195-195             V108 196-199              
   V109 200-200             V110 201-201             V111 202-203              
   V112 204-204             V113 205-208             V114 209-209              
   V115 210-210             V116 211-215             V117 216-217              
   V118 218-218             V119 219-220             V120 221-221              
   V121 222-225             V122 226-226             V123 227-229              
   V124 230-230             V125 231-231             V126 232-232              
   V127 233-235             V128 236-236             V129 237-237              
   V130 238-241             V131 242-242             V132 243-243              
   V133 244-244             V134 245-247             V135 248-248              
   V136 249-249             V137 250-250             V138 251-253              
   V139 254-254             V140 255-255             V141 256-256              
   V142 257-259             V143 260-260             V144 261-261              
   V145A 262-263            V145B 264-265            V145C 266-267             
   V146 268-268             V147 269-270             V148 271-274              
   V149 275-275             V150 276-276             V151 277-277              
   V152 278-278             V153 279-279             V154 280-280              
   V155 281-281             V156 282-282             V157 283-283              
   V158 284-284             V159 285-285             V160 286-287              
   V161 288-288             V162 289-289             V163A 290-291             
   V163B 292-293            V163C 294-295            V164 296-297              
   V165 298-298             V166 299-302             V167 303-304              
   V168 305-305             V169 306-307             V170 308-309              
   V171 310-311             V172 312-313             V173 314-315              
   V174 316-317             V175 318-319             V176 320-320              
   V177 321-325             V178 326-327             V179 328-328              
   V180 329-329             V181 330-334             V182 335-335              
   V183 336-340             V184 341-342             V185 343-345              
   V186 346-349             V187 350-353             V188 354-355              
   V189 356-356             V190 357-357             V191 358-358              
   V192 359-359             V193 360-360             V194 361-362              
   V195 363-363             V196 364-364             V197 365-366              
   V198 367-372             V199 373-373             V200 374-375              
   V201 376-376             V202 377-377             V203 378-382              
   V204 383-388             V205 389-390             V206 391-391              
   V207 392-392             V208 393-397             V209 398-399              
   V210 400-404             V211 405-406             V212 407-411              
   V213 412-413             V214 414-415             V215 416-417              
   V216 418-419             V217 420-424             V218 425-426              
   V219 427-428             V220 429-429             V221 430-436              
   V222 437-437             V223 438-439             V224 440-440              
   V225 441-446             V226 447-447             V227 448-448              
   V228 449-455             V229 456-456             V230 457-458              
   V231 459-460             V232 461-462             V233 463-464              
   V234 465-466             V235 467-468             V236A 469-469             
   V236B 470-470            V237A 471-471            V237B 472-472             
   V238A 473-474            V238B 475-476            V239 477-477              
   V240 478-478             V241 479-479             V242 480-481              
   V243 482-482             V244 483-483             V245 484-484              
   V246 485-485             V247 486-490             V248 491-491              
   V249 492-492             V250 493-497             V251 498-498              
   V252 499-499             V253 500-504             V254 505-505              
   V255 506-510             V256 511-511             V257 512-516              
   V258 517-517             V259 518-522             V260 523-523              
   V261 524-528             V262 529-529             V263 530-530              
   V264 531-535             V265 536-536             V266 537-537              
   V267 538-543             V268 544-544             V269 545-547              
   V270 548-549             V271 550-550             V272 551-551              
   V273 552-557             V274 558-559             V275 560-560              
   V276 561-566             V277 567-567             V278 568-569              
   V279 570-575             V280 576-577             V281 578-583              
   V282 584-585             V283 586-586             V284 587-592              
   V285 593-593             V286 594-595             V287 596-596              
   V288 597-597             V289 598-598             V290 599-600              
   V291 601-601             V292 602-602             V293 603-603              
   V294 604-604             V295 605-605             V296 606-606              
   V297 607-607             V298 608-608             V299 609-610              
   V300 611-612             V301 613-613             V302 614-615 .1           
   V303 616-617 .1          V304 618-619             V305 620-621              
   V306 622-624             V307 625-626             V308A 627-628             
   V308B 629-630            V309 631-634             V310 635-635              
   V311 636-636             V312 637-641             V313 642-643              
   V314 644-644             V315 645-651             V316 652-652              
   V317 653-653             V318 654-655             V319 656-656              
   V320 657-663             V321 664-664             V322 665-665              
   V323 666-666             V324 667-667             V325 668-668              
   V326 669-669             V327 670-670             V328 671-671              
   V329 672-677             V330 678-678             V331 679-679              
   V332 680-681;                                                               
                                                                               
* SAS LABEL STATEMENT;                                                         
                                                                               
LABEL                                                                          
   V1 = "SSA STUDY NUMBER - 3600"                                              
   V2 = "INTERVIEW NUMBER"                                                     
   V3 = "SU WEIGHT VARIABLE"                                                   
   V4 = "SAMPLE BOOK NUMBER"                                                   
   V5 = "REGION"                                                               
   V6 = "STANDARD METRO AREA"                                                  
   V7 = "PLACE CODE"                                                           
   V8 = "SAMPLE SPLIT"                                                         
   V9 = "SAMPLE RATIO"                                                         
   V10 = "RATING OF SAMPLE ADDRESS"                                            
   V11 = "TYPE OF BLOCK"                                                       
   V12 = "DATE OF INTERVIEW"                                                   
   V13 = "INTERVIEWER NUMBER"                                                  
   V14 = "SPENDING UNIT COMPOSITON"                                            
   V15 = "IS R HEAD OF SU"                                                     
   V16 = "NUMBER OF ADULTS IN SU"                                              
   V17 = "ANY CHILDREN < 18 YEARS"                                             
   V18 = "X# CHILDREN < 18 YEARS"                                              
   V19 = "XAGE OF YOUNGEST CHILD"                                              
   V20 = "XAGE OF OLDEST CHILD <18"                                            
   V21 = "# (ADULT+CHILDREN) IN SU"                                            
   V22 = "BTR/WRS FNCLY THN YR AGO"                                            
   V23 = "MR/LS MONEY THAN YR AGO"                                             
   V24A = "WHY FIN STATUS DIFFERENT"                                           
   V24B = "WHY FIN STATUS DIFFERENT"                                           
   V24C = "WHY FIN STATUS DIFFERENT"                                           
   V25 = "MAKE MR/LS MONEY NEXT YR"                                            
   V26A = "RSN MR/LS MONEY NEXT YR"                                            
   V26B = "RSN MR/LS MONEY NEXT YR"                                            
   V27 = "NATL FUTURE-GD/BD TIMES"                                             
   V28A = "RSN XPCT GD/BD NATL TIME"                                           
   V28B = "RSN XPCT GD/BD NATL TIME"                                           
   V29 = "HW LONG LIVED THIS HOUSE"                                            
   V30 = "NUMBER ROOMS FOR SU"                                                 
   V31 = "R BUY NEW HOME IN 1954?"                                             
   V32 = "DOES R OWN OR RENT HOME"                                             
   V33 = "XWHY NEITHER OWNS/RENTS"                                             
   V34 = "XDID R EVER OWN HOME"                                                
   V35 = "XWHEN DID R OWN HOME"                                                
   V36 = "XRSN HOME WAS GIVEN UP"                                              
   V37 = "XAMOUNT RENT PER MONTH"                                              
   V38 = "XWN BOUGHT CURRENT HOME"                                             
   V39 = "XHOUSE-NEW/LIVED IN BFR"                                             
   V40 = "XIS HOUSE VALUE ASSIGNED"                                            
   V41 = "XPRESENT HOUSE VALUE"                                                
   V42 = "XHAVE MORTGAGE ON HOME?"                                             
   V43 = "XFHA OR VA MORTGAGE-HOME"                                            
   V44 = "XHAVE 2ND MORTGAGE-HOME"                                             
   V45 = "XIS MORTGAGE VALUE ASGND"                                            
   V46 = "XTTL $ PRESENT MORTGAGE"                                             
   V47 = "XMORTGAGE PAYMENT-$/MNTH"                                            
   V48 = "XMRTGE-WHY PAID $ > PYMT"                                            
   V49 = "XIS THIS 1ST HOME OWNED"                                             
   V50 = "XAGE R BECAME HOMEOWNER"                                             
   V51A = "COMPARE-THIS HOUSE AND LST"                                         
   V51B = "COMPARE-THIS HOUSE AND LST"                                         
   V52 = "XHOUSE LRGR/SMR THN LAST"                                            
   V53 = "XTHIS HS MR/LS VALUABLE"                                             
   V54 = "XPCT BUY/BUILD HS IN '55"                                            
   V55 = "XPLAN BUY HOUSE IN '56"                                              
   V56A = "XREASON BUY/BUILD HOUSE"                                            
   V56B = "XREASON BUY/BUILD HOUSE"                                            
   V57 = "XWL FUTURE HOUSE BE NEW"                                             
   V58 = "XCOST-FUTURE HOUSE AND LOT"                                          
   V59 = "XR SETTLD IN PSNT HOUSE?"                                            
   V60A = "XRSN (NT)SETTLED PSNT HS"                                           
   V60B = "XRSN (NT)SETTLED PSNT HS"                                           
   V61 = "PRESENT HOME MEET NEEDS?"                                            
   V62 = "RSN PSNT HOME MEET NEEDS"                                            
   V63 = "XNEED MR/LS SPACE-HOME"                                              
   V64 = "HV 1954 UPKEEP EXPENSES"                                             
   V65A = "XADDITIONS-WHAT WAS DONE"                                           
   V65B = "XADDITIONS-WHAT WAS DONE"                                           
   V66A = "XREPAIRS-WHAT WAS DONE"                                             
   V66B = "XREPAIRS-WHAT WAS DONE"                                             
   V67 = "XCOST '54 HOME ADDITIONS"                                            
   V68 = "XCOST '54 HOME REPAIRS"                                              
   V69 = "XCOST-'54 ADDTNS AND REPAIRS"                                        
   V70 = "XDEBT?-'54 REPAIR/ADDTNS"                                            
   V71 = "X$ LEFT PAY-HOME IMPRVT"                                             
   V72 = "XMORTGAGE INCLD REPAIRS?"                                            
   V73 = "R PLAN '55 HOME EXPNDTRS"                                            
   V74 = "X'55 HOME EXPNDTR-ADDTNS"                                            
   V75 = "X'55 HOME EXPNDTR-REPAIR"                                            
   V76 = "XIMPPVT-$ WL SPEND(BRKT)"                                            
   V77 = "XAMOUNT WL SPEND-IMPRVT"                                             
   V78 = "XHOW WL FIN HOME EXPNDTR"                                            
   V79 = "BRKT-PRESENT HOUSE VALUE"                                            
   V80 = "BRKT-AMT MORTGAGE DEBT"                                              
   V81 = "BRKT-AMT MORTGAGE PYMT"                                              
   V82 = "BRKT-$ FOR HOME IMPRVT"                                              
   V83 = "BRKT-HOME IMPRVT DEBT"                                               
   V84 = "DOES R(WIFE) OWN A CAR"                                              
   V85 = "X# R'S CARS-GOT NEW/USED"                                            
   V86 = "XBOUGHT NEW/USED CAR-'54"                                            
   V87 = "XOTRS IN FAM OWNING CAR"                                             
   V88 = "XBUY CRNT CAR NEW/USED"                                              
   V89 = "XMAKE OF CAR OWNED"                                                  
   V90 = "XYEAR OF CAR OWNED"                                                  
   V91 = "XYEAR R BOUGHT CRNT CAR"                                             
   V92 = "XWN IN '54 DID R BUY CAR"                                            
   V93 = "XTOTAL $$-CAR BOUGHT '54"                                            
   V94 = "XTRADE-IN/SELL CAR-'54"                                              
   V95 = "X$ CAR TRADE-IN/SALE-'54"                                            
   V96 = "XYEAR CAR TRADE/SOLD-'54"                                            
   V97 = "XYR BUY CAR TRADED IN 54"                                            
   V98 = "XHOW FNCD CAR BOUGHT '54"                                            
   V99 = "X$ LEFT PAY-'54 CAR BUY"                                             
   V100 = "XOWE $-CAR GOT PRE-'54"                                             
   V101 = "XTTL DEBT-ALL CARS OWNED"                                           
   V102 = "XMAKE REGULAR CAR PYMTS"                                            
   V103 = "XDISPOSED OTR CAR IN '54"                                           
   V104 = "XYR OTR CAR DISPOSD '54"                                            
   V105 = "XYR BUY DISPOSED CAR-'54"                                           
   V106 = "EXPECT TO BUY CAR IN '55"                                           
   V107 = "XWL BUY NEW/USED CAR-'55"                                           
   V108 = "X$ XPCT PAY FOR CAR-'55"                                            
   V109 = "XWN IN 1955 WILL BUY CAR"                                           
   V110 = "XHW FINANCE CAR WILL BUY"                                           
   V111 = "XWN MIGHT BUY CAR-'56>?"                                            
   V112 = "XDOES R TRADE CARS RGLRY"                                           
   V113 = "TTL VALUE OF CARS OWNED"                                            
   V114 = "BRKT-PRICE OF CAR P '54"                                            
   V115 = "BRKT-XPCTD COST CAR P'55"                                           
   V116 = "NET OUTLAY ON CAR P'54"                                             
   V117 = "BRKT-NET OUTLAY CAR P'54"                                           
   V118 = "BRKT-DEBT ON ALL SU CARS"                                           
   V119 = "BRKT-VALUE CARS OWNED"                                              
   V120 = "BRKT-COST HSLD DURABLES"                                            
   V121 = "TOTAL COST HSLD DURABLES"                                           
   V122 = "XAMT RECD DURABLE TRD-IN"                                           
   V123 = "XACTL $ DURABLE TRADE-IN"                                           
   V124 = "XBUY DURABLES WITH CASH?"                                           
   V125 = "DID R BUY TV IN 1954"                                               
   V126 = "XTRADE-IN/SELL OLD TV"                                              
   V127 = "XCOST OF TV BOUGHT '54"                                             
   V128 = "XBUY TV CASH/INSTLMT-'54"                                           
   V129 = "DID R BUY FURNITURE-'54"                                            
   V130 = "XCOST FURNITURE BUY '54"                                            
   V131 = "XBUY FRNTR CASH/INSTLMNT"                                           
   V132 = "BUY REFRIGERATOR IN '54?"                                           
   V133 = "XTRD-IN/SELL OLD REFGR"                                             
   V134 = "XCOST-'54 REFRIGERTR BUY"                                           
   V135 = "XBUY RFRGR CASH/INSTLMNT"                                           
   V136 = "DID R BUY WASHER IN '54"                                            
   V137 = "XTRADE-IN/SELL OLD WSHR"                                            
   V138 = "XCOST OF WASHER BUY '54"                                            
   V139 = "XBUY WASHER CASH/INSTLMT"                                           
   V140 = "DID R BUY STOVE IN '54"                                             
   V141 = "XTRADE-IN/SELL OLD STOVE"                                           
   V142 = "XCOST STOVE BOUGHT IN 54"                                           
   V143 = "XBUY STOVE CASH/INSTLMNT"                                           
   V144 = "BUY 2/MR WSHRS, TV'S ETC"                                           
   V145A = "OTR DURABLES BOUGHT-'54"                                           
   V145B = "OTR DURABLES BOUGHT-'54"                                           
   V145C = "OTR DURABLES BOUGHT-'54"                                           
   V146 = "WILL BUY DURABLES IN '55"                                           
   V147 = "X55 DURABLE-BRKT XPCTD $"                                           
   V148 = "XDURABLE-$ XPCT SPEND-55"                                           
   V149 = "X55 DURABLES-XPCTD FNCS"                                            
   V150 = "XTV-AMT WL SPEND IN '55"                                            
   V151 = "X55 WL BUY TV CASH/CRDT"                                            
   V152 = "XWHEN IN '55 WILL BUY TV"                                           
   V153 = "XFRNTR-$ WL SPEND IN '55"                                           
   V154 = "XWL BUY FRNTR CASH/CRDT"                                            
   V155 = "55-RFRGR-FREEZR COMBINED"                                           
   V156 = "XRFRGR-$ WL SPEND IN '55"                                           
   V157 = "XWL BUY RFRGR CASH/CRDT"                                            
   V158 = "XWN IN '55 WL BUY RFRGR"                                            
   V159 = "55-WASHER-DRYER COMBINED"                                           
   V160 = "XWSHR-$ WL SPEND IN '55"                                            
   V161 = "XWL BUY WSHR CASH/CREDIT"                                           
   V162 = "XWHEN IN '55 WL BUY WSHR"                                           
   V163A = "OTR DRBLS XPCTS BUY '55"                                           
   V163B = "OTR DRBLS XPCTS BUY '55"                                           
   V163C = "OTR DRBLS XPCTS BUY '55"                                           
   V164 = "HOW FAMILY BUDGETS"                                                 
   V165 = "HOME PURCHASES-HOW FNCD?"                                           
   V166 = "AMOUNT OF MEDICAL DEBT"                                             
   V167 = "BRACKET ON MEDICAL DEBT"                                            
   V168 = "IS R.E. DEBT ASSIGNED"                                              
   V169 = "R.E. DEBT OTHER THN HOME"                                           
   V170 = "LIFE INSURANCE DEBT"                                                
   V171 = "DEBT TO A STOCKBROKER"                                              
   V172 = "DEBT TO PVT INDIVIDUALS"                                            
   V173 = "DEBT TO A BANK"                                                     
   V174 = "DEBT TO LOAN/FINANCE CO"                                            
   V175 = "DEBT ON OTHER PURCHASES"                                            
   V176 = "TTL DEBT-VALUE ASSIGNED?"                                           
   V177 = "AMOUNT TOTAL DEBT IN $"                                             
   V178 = "BRKT-AMOUNT TOTAL DEBT"                                             
   V179 = "ANY DEBT FOR BSN PURPOSE"                                           
   V180 = "IS PERSONAL DEBT ASGND?"                                            
   V181 = "AMT TOTAL PERSONAL DEBT"                                            
   V182 = "BRKT TOTAL PERSONAL DEBT"                                           
   V183 = "PRSNL DEBT RGLRY REPAID"                                            
   V184 = "BRKT-DEBT RGLRY REPAID"                                             
   V185 = "AMT OF REGULAR DEBT PAY"                                            
   V186 = "TOTAL DEBT-BANK/LOAN CO"                                            
   V187 = "DURABLES DEBT-1954 AND '55"                                         
   V188 = "DEBT-AS % TOTAL INC"                                                
   V189 = "BRKT-DEBT % TOTAL INC"                                              
   V190 = "% INC TO DEBT REPAYMENT"                                            
   V191 = "RATE OF DEBT EXTINCTION"                                            
   V192 = "SHORT TERM DEBT PAYMENTS"                                           
   V193 = "HEAD'S EMPLOYMENT STATUS"                                           
   V194 = "HEAD'S OCCUPATION"                                                  
   V195 = "HEAD WORK FOR SELF/OTHER"                                           
   V196 = "XDOES HEAD EMPLOY OTHERS"                                           
   V197 = "XTTL 1954 FARM RECEIPTS"                                            
   V198 = "X1954 NET FARM INCOME"                                              
   V199 = "OWN/HV BUSINESS INTST-54"                                           
   V200 = "XTYPE BUSINESS OWNED-'54"                                           
   V201 = "XOWNER/PARTNER IN BUSN?"                                            
   V202 = "XIS BUSINESS CORPORATED?"                                           
   V203 = "X$ TKN FRM BUSN IN '54"                                             
   V204 = "XAMT BUSN PROFIT/LOSS"                                              
   V205 = "XBRKT-NET BUSINESS INC"                                             
   V206 = "XBUSN DEBT PAID-HOW CNSD"                                           
   V207 = "TYPE STOCK OWNED, IF ANY"                                           
   V208 = "XVAL PUBLIC STOCK OWNED"                                            
   V209 = "XBRKT-VALUE PUBLIC STOCK"                                           
   V210 = "SU'S WAGE AND SALARY INCOME"                                        
   V211 = "WAGE AND SALARY INCOME-CI"                                          
   V212 = "PRFNL AND SELF-EMPLT INCOME"                                        
   V213 = "PRFNL/SELF-EMPLT INC-CI"                                            
   V214 = "FARMING INC (NON-FMR)-CI"                                           
   V215 = "INC-ROOMERS/BOARDERS-CI"                                            
   V216 = "INC-TRANSFER PAYMENTS-CI"                                           
   V217 = "INC-RENT, INTST, DVDNDS"                                            
   V218 = "RENTAL INCOME ONLY-CI"                                              
   V219 = "INC-INTEREST AND DVDNDS-CI"                                         
   V220 = "TTL '54 INCOME AND TAX ASGND"                                       
   V221 = "SU'S TOTAL 1954 INCOME"                                             
   V222 = "BRKT TOTAL 1954 INCOME"                                             
   V223 = "1954 TOTAL INCOME DECILE"                                           
   V224 = "'54 INCOME TAX ASSIGNED?"                                           
   V225 = "AMT SU'S 1954 INCOME TAX"                                           
   V226 = "BRKT-AMT 1954 INCOME TAX"                                           
   V227 = "'54 DISPOSABLE INC ASGND"                                           
   V228 = "TTL 1954 DISPOSABLE INC"                                            
   V229 = "BRKT-1954 DISPOSABLE INC"                                           
   V230 = "54 DISPOSABLE INC DECILE"                                           
   V231 = "W.H'S WAGES AND SALARY-CI"                                          
   V232 = "W.H'S TOTAL INCOME-CI"                                              
   V233 = "OTR'S WAGES/SALARIES-CI"                                            
   V234 = "OTHER'S TOTAL INCOME-CI"                                            
   V235 = "W.H AND OTR'S TOTAL INC-CI"                                         
   V236A = "OTHER TYPES INCOME-WIFE"                                           
   V236B = "OTHER TYPES INCOME-WIFE"                                           
   V237A = "OTHER TYPES INC-OTHERS"                                            
   V237B = "OTHER TYPES INC-OTHERS"                                            
   V238A = "OTR MEMBER-RELATION TO H"                                          
   V238B = "OTR MEMBER-RELATION TO H"                                          
   V239 = "% SU'S INC EARN BY WOMEN"                                           
   V240 = "# INCOME RECEIVERS IN SU"                                           
   V241 = "SU TAX RETURNS-# PAID"                                              
   V242 = "# TAX EXEMPTIONS IN SU"                                             
   V243 = "TOTAL 1953 INCOME-CI"                                               
   V244 = "COMPARE-'53 AND '54 INCOME"                                         
   V245 = "BSN FUNDS-KEPT SEPARATE?"                                           
   V246 = "VAL SAVINGS BOND ASGND?"                                            
   V247 = "VALUE WAR/SAVINGS BONDS"                                            
   V248 = "BRKT-VAL WAR/SVNGS BONDS"                                           
   V249 = "VAL CURRENT BONDS ASGND?"                                           
   V250 = "VAL CURRENT INTST BONDS"                                            
   V251 = "BRKT-VAL CURRENT BONDS"                                             
   V252 = "AMT CHECKING ACNT ASGND?"                                           
   V253 = "AMT SU'S CHECKING ACNTS"                                            
   V254 = "BRKT-AMT IN CHCKNG ACNTS"                                           
   V255 = "AMOUNT SU'S BANK SAVINGS"                                           
   V256 = "BRKT-AMT SAVINGS IN BANK"                                           
   V257 = "VALUE ACNTS-SAVINGS ASCN"                                           
   V258 = "BRKT-ACNTS W SAVING ASCN"                                           
   V259 = "AMT HELD IN CRDT UNIONS"                                            
   V260 = "BRKT-CRDT UNION HOLDINGS"                                           
   V261 = "AMT SU'S POSTAL SAVINGS"                                            
   V262 = "BRKT-AMT POSTAL SAVINGS"                                            
   V263 = "TOTAL AMT SAVINGS ASGND?"                                           
   V264 = "TOTAL SU'S SAVINGS ACNTS"                                           
   V265 = "BRKT-AMT TOTAL SAVINGS"                                             
   V266 = "AMT LIQUID ASSETS ASGND?"                                           
   V267 = "SU'S TOTAL LIQUID ASSETS"                                           
   V268 = "BRKT-VALUE LIQUID ASSETS"                                           
   V269 = "LIQUID ASSETS-% TTL INC"                                            
   V270 = "BRKT-LQD ASSET % TTL INC"                                           
   V271 = "LIQUID ASSET-DEBT RELN"                                             
   V272 = "BRKT-1953 LIQUID ASSETS"                                            
   V273 = "CHANGE-BONDS FACE VALUE"                                            
   V274 = "BRKT-CHNG BONDS FACE VAL"                                           
   V275 = "GOVT BONDS-ACCRUAL CHNG"                                            
   V276 = "NET CHANGE IN GOVT BONDS"                                           
   V277 = "BRKT BONDS-ACCRUAL CHNG"                                            
   V278 = "BRKT-NET CHANGE BOND VAL"                                           
   V279 = "CHECKING ACNT-AMT CHANGE"                                           
   V280 = "BRKT-CHECKING ACNT CHNG"                                            
   V281 = "SAVINGS ACNTS-AMT CHANGE"                                           
   V282 = "BRKT-SAVINGS ACNT CHANGE"                                           
   V283 = "LQD ASSETS-ACCRUAL CHNG"                                            
   V284 = "TTL LIQUID ASSET CHANGE"                                            
   V285 = "BRKT L.A.-ACCRUAL CHNG"                                             
   V286 = "BRKT-LIQUID ASSET CHANGE"                                           
   V287 = "ANY SPECIAL BANK ACNTS"                                             
   V288 = "# DEPENDENTS NOT IN SU"                                             
   V289 = "LENGTH OF R'S MARRIAGE"                                             
   V290 = "AGE OF HEAD OF SU"                                                  
   V291 = "EDUCATION OF HEAD OF SU"                                            
   V292 = "ANY VETERANS IN SU?"                                                
   V293 = "SEX OF HEAD OF SU"                                                  
   V294 = "SEX OF RESPONDENT"                                                  
   V295 = "RACE OF RESPONDENT"                                                 
   V296 = "FILTER-FAM DATA STATUS"                                             
   V297 = "FAMILY COMPOSITION"                                                 
   V298 = "# ADULTS IN FAMILY"                                                 
   V299 = "# CHLDN < 18 YRS IN FAM"                                            
   V300 = "AGE YOUNGEST CHLD IN FAM"                                           
   V301 = "# (CHLDRN+ADULTS) IN FAM"                                           
   V302 = "# ROOMS/FAMILY MEMBER"                                              
   V303 = "# ROOMS/EQUIVALENT ADULT"                                           
   V304 = "HOUSE VAL/FAMILY MEMBER"                                            
   V305 = "HOUSE VAL/EQVLNT ADULT"                                             
   V306 = "RATIO-HOUSE VALUE-INCOME"                                           
   V307 = "BRKT-RATIO HOUSE VAL-INC"                                           
   V308A = "DURABLES FAMILY BOUGHT"                                            
   V308B = "DURABLES FAMILY BOUGHT"                                            
   V309 = "DURABLES-$ FAMILY SPENT"                                            
   V310 = "DURABLES-BRKT FAM XPNDTR"                                           
   V311 = "FAM PRSNL DEBT ASSIGNED?"                                           
   V312 = "AMT FAMILY PERSONAL DEBT"                                           
   V313 = "BRKT-FAM PERSONAL DEBT"                                             
   V314 = "FAMILY INCOME ASSIGNED?"                                            
   V315 = "TOTAL 1954 FAMILY INCOME"                                           
   V316 = "BRKT-1954 FAMILY INCOME"                                            
   V317 = "FAMILY INCOME QUINTILE"                                             
   V318 = "URBN-RURAL INC QUINTILE"                                            
   V319 = "'54DISPOSBL FAM INC ASGN"                                           
   V320 = "1954 DISPOSABLE FAM INC"                                            
   V321 = "BRKT-'54DISPOSBL FAM INC"                                           
   V322 = "# INC RECEIVERS IN FAM"                                             
   V323 = "# TAX RETURNS FAM PAID"                                             
   V324 = "#TAX EXEMPTIONS IN FAM"                                             
   V325 = "BRKT-TAXABLE FAMILY INC"                                            
   V326 = "H.H AND W.H'S TAXABLE INC"                                          
   V327 = "TAXABLE INC-OTR FAM MBRS"                                           
   V328 = "FAM LIQUID ASSETS ASGND?"                                           
   V329 = "AMT FAMILY LIQUID ASSETS"                                           
   V330 = "BRKT-FAM LIQUID ASSETS"                                             
   V331 = "# DEPENDENTS OUTSIDE FAM"                                           
   V332 = "FAMILY WEIGHT VARIABLE";                                            
                                                                               
* USER-DEFINED MISSING VALUE RECODE TO SAS SYSMIS;                             
                                                                               
/*                                                                             
   IF V6 GE 0000009 THEN V6=.;         IF V7=0000000 THEN V7=.;                
   IF V8 GE 0000009 THEN V8=.;         IF V10 GE 0000009 THEN V10=.;           
   IF V11=0000000 THEN V11=.;          IF V12 GE 0000009 THEN V12=.;           
   IF V14 GE 0000099 THEN V14=.;       IF V15 GE 0000009 THEN V15=.;           
   IF V16=0000000 THEN V16=.;          IF V17 GE 0000009 THEN V17=.;           
   IF V18 GE 0000091 OR V18=0000000 THEN V18=.;                                
   IF V19 GE 0000091 OR V19=0000000 THEN V19=.;                                
   IF V20 GE 0000009 OR V20=0000000 THEN V20=.;                                
   IF V21=0000000 THEN V21=.;          IF V22 GE 0000008 THEN V22=.;           
   IF V23 GE 0000007 THEN V23=.;       IF V24A=0000000 THEN V24A=.;            
   IF V24B=0000000 THEN V24B=.;        IF V24C=0000000 THEN V24C=.;            
   IF V25 GE 0000007 THEN V25=.;                                               
   IF V26A GE 0000098 OR V26A=0000000 THEN V26A=.;                             
   IF V26B GE 0000098 OR V26B=0000000 THEN V26B=.;                             
   IF V27 GE 0000008 THEN V27=.;                                               
   IF V28A GE 0000095 OR V28A=0000000 THEN V28A=.;                             
   IF V28B GE 0000095 OR V28B=0000000 THEN V28B=.;                             
   IF V29 GE 0000099 THEN V29=.;                                               
   IF V30 GE 0000091 OR V30=0000000 THEN V30=.;                                
   IF V31 GE 0000009 OR V31=0000000 THEN V31=.;                                
   IF V32 GE 0000099 OR V32=0000000 THEN V32=.;                                
   IF V33=0000000 THEN V33=.;                                                  
   IF V34 GE 0000009 OR V34=0000000 THEN V34=.;                                
   IF V35 GE 0000091 THEN V35=.;                                               
   IF V36 GE 0000099 OR V36=0000000 THEN V36=.;                                
   IF V37 GE 0000999 OR V37=0000000 THEN V37=.;                                
   IF V38 GE 0000099 OR V38=0000000 THEN V38=.;                                
   IF V39 GE 0000009 OR V39=0000000 THEN V39=.;                                
   IF V40 GE 0000009 OR V40=0000000 THEN V40=.;                                
   IF V41=0000000 THEN V41=.;                                                  
   IF V42 GE 0000009 OR V42=0000000 THEN V42=.;                                
   IF V43 GE 0000009 OR V43=0000000 THEN V43=.;                                
   IF V44 GE 0000009 OR V44=0000000 THEN V44=.;                                
   IF V45 GE 0000009 OR V45=0000000 THEN V45=.;                                
   IF V46=0000000 THEN V46=.;                                                  
   IF V47 GE 0000999 OR V47=0000000 THEN V47=.;                                
   IF V48 GE 0000009 OR V48=0000000 THEN V48=.;                                
   IF V49 GE 0000008 OR V49=0000000 THEN V49=.;                                
   IF V50 GE 0000091 THEN V50=.;       IF V51A GE 0000098 THEN V51A=.;         
   IF V51B GE 0000098 THEN V51B=.;                                             
   IF V52 GE 0000008 OR V52=0000000 THEN V52=.;                                
   IF V53 GE 0000008 OR V53=0000000 THEN V53=.;                                
   IF V54 GE 0000007 THEN V54=.;                                               
   IF V55 GE 0000009 OR V55=0000000 THEN V55=.;                                
   IF V56A GE 0000009 OR V56A=0000000 THEN V56A=.;                             
   IF V56B GE 0000009 OR V56B=0000000 THEN V56B=.;                             
   IF V57 GE 0000008 OR V57=0000000 THEN V57=.;                                
   IF V58 GE 0000091 THEN V58=.;                                               
   IF V59 GE 0000008 OR V59=0000000 THEN V59=.;                                
   IF V60A GE 0000091 THEN V60A=.;     IF V60B GE 0000091 THEN V60B=.;         
   IF V61 GE 0000008 THEN V61=.;                                               
   IF V62 GE 0000099 THEN V62=.;       IF V63 GE 0000008 THEN V63=.;           
   IF V64 GE 0000009 OR V64=0000000 THEN V64=.;                                
   IF V65A GE 0000091 THEN V65A=.;     IF V65B GE 0000091 THEN V65B=.;         
   IF V66A GE 0000091 THEN V66A=.;     IF V66B GE 0000091 THEN V66B=.;         
   IF V67 GE 0000009 OR V67=0000000 THEN V67=.;                                
   IF V68 GE 0000009 OR V68=0000000 THEN V68=.;                                
   IF V69 GE 0009999 OR V69=0000000 THEN V69=.;                                
   IF V70 GE 0000009 OR V70=0000000 THEN V70=.;                                
   IF V71 GE 0009999 OR V71=0000000 THEN V71=.;                                
   IF V72 GE 0000009 OR V72=0000000 THEN V72=.;                                
   IF V73 GE 0000008 OR V73=0000000 THEN V73=.;                                
   IF V74 GE 0000009 OR V74=0000000 THEN V74=.;                                
   IF V75 GE 0000099 OR V75=0000000 THEN V75=.;                                
   IF V76 GE 0000009 OR V76=0000000 THEN V76=.;                                
   IF V77 GE 0000999 OR V77=0000000 THEN V77=.;                                
   IF V78 GE 0000008 OR V78=0000000 THEN V78=.;                                
   IF V79 GE 0000009 OR V79=0000000 THEN V79=.;                                
   IF V80=0000000 THEN V80=.;                                                  
   IF V81 GE 0000099 OR V81=0000000 THEN V81=.;                                
   IF V82 GE 0000009 OR V82=0000000 THEN V82=.;                                
   IF V83 GE 0000009 OR V83=0000000 THEN V83=.;                                
   IF V84 GE 0000009 THEN V84=.;       IF V85 GE 0000098 THEN V85=.;           
   IF V86 GE 0000009 OR V86=0000000 THEN V86=.;                                
   IF V87 GE 0000009 THEN V87=.;                                               
   IF V88 GE 0000009 OR V88=0000000 THEN V88=.;                                
   IF V89 GE 0000098 OR V89=0000000 THEN V89=.;                                
   IF V90 GE 0000098 OR V90=0000000 THEN V90=.;                                
   IF V91 GE 0000098 OR V91=0000000 THEN V91=.;                                
   IF V92 GE 0000008 OR V92=0000000 THEN V92=.;                                
   IF V93 GE 0009999 OR V93=0000000 THEN V93=.;                                
   IF V94 GE 0000009 OR V94=0000000 THEN V94=.;                                
   IF V95 GE 0009999 OR V95=0000000 THEN V95=.;                                
   IF V96 GE 0000099 OR V96=0000000 THEN V96=.;                                
   IF V97 GE 0000099 OR V97=0000000 THEN V97=.;                                
   IF V98 GE 0000008 OR V98=0000000 THEN V98=.;                                
   IF V99 GE 0000009 OR V99=0000000 THEN V99=.;                                
   IF V100 GE 0000009 OR V100=0000000 THEN V100=.;                             
   IF V101 GE 0009999 OR V101=0000000 THEN V101=.;                             
   IF V102 GE 0000009 OR V102=0000000 THEN V102=.;                             
   IF V103 GE 0000009 THEN V103=.;                                             
   IF V104 GE 0000099 OR V104=0000000 THEN V104=.;                             
   IF V105 GE 0000099 OR V105=0000000 THEN V105=.;                             
   IF V106 GE 0000008 THEN V106=.;                                             
   IF V107 GE 0000008 OR V107=0000000 THEN V107=.;                             
   IF V108 GE 0009999 OR V108=0000000 THEN V108=.;                             
   IF V109 GE 0000008 OR V109=0000000 THEN V109=.;                             
   IF V110 GE 0000008 OR V110=0000000 THEN V110=.;                             
   IF V111 GE 0000098 OR V111=0000000 THEN V111=.;                             
   IF V112 GE 0000008 OR V112=0000000 THEN V112=.;                             
   IF V113 GE 0009999 OR V113=0000000 THEN V113=.;                             
   IF V114 GE 0000009 OR V114=0000000 THEN V114=.;                             
   IF V115 GE 0000009 OR V115=0000000 THEN V115=.;                             
   IF V116 GE 0009998 THEN V116=.;     IF V117 GE 0000091 THEN V117=.;         
   IF V118 GE 0000009 OR V118=0000000 THEN V118=.;                             
   IF V119 GE 0000091 THEN V119=.;                                             
   IF V120 GE 0000008 OR V120=0000000 THEN V120=.;                             
   IF V121 GE 0009999 OR V121=0000000 THEN V121=.;                             
   IF V122 GE 0000008 OR V122=0000000 THEN V122=.;                             
   IF V123 GE 0000999 OR V123=0000000 THEN V123=.;                             
   IF V124 GE 0000009 OR V124=0000000 THEN V124=.;                             
   IF V125=0000000 THEN V125=.;                                                
   IF V126 GE 0000009 OR V126=0000000 THEN V126=.;                             
   IF V127 GE 0000999 OR V127=0000000 THEN V127=.;                             
   IF V128 GE 0000009 OR V128=0000000 THEN V128=.;                             
   IF V129=0000000 THEN V129=.;                                                
   IF V130 GE 0009999 OR V130=0000000 THEN V130=.;                             
   IF V131 GE 0000009 OR V131=0000000 THEN V131=.;                             
   IF V132=0000000 THEN V132=.;                                                
   IF V133 GE 0000009 OR V133=0000000 THEN V133=.;                             
   IF V134 GE 0000999 OR V134=0000000 THEN V134=.;                             
   IF V135 GE 0000009 OR V135=0000000 THEN V135=.;                             
   IF V136=0000000 THEN V136=.;                                                
   IF V137 GE 0000009 OR V137=0000000 THEN V137=.;                             
   IF V138 GE 0000999 OR V138=0000000 THEN V138=.;                             
   IF V139 GE 0000009 OR V139=0000000 THEN V139=.;                             
   IF V140=0000000 THEN V140=.;                                                
   IF V141 GE 0000009 OR V141=0000000 THEN V141=.;                             
   IF V142 GE 0000999 OR V142=0000000 THEN V142=.;                             
   IF V143 GE 0000009 OR V143=0000000 THEN V143=.;                             
   IF V144 GE 0000009 OR V144=0000000 THEN V144=.;                             
   IF V145A=0000000 THEN V145A=.;      IF V145B GE 0000009 THEN V145B=.;       
   IF V145C=0000000 THEN V145C=.;      IF V146 GE 0000009 THEN V146=.;         
   IF V147 GE 0000091 THEN V147=.;                                             
   IF V148 GE 0009999 OR V148=0000000 THEN V148=.;                             
   IF V149 GE 0000009 OR V149=0000000 THEN V149=.;                             
   IF V150 GE 0000009 OR V150=0000000 THEN V150=.;                             
   IF V151 GE 0000009 OR V151=0000000 THEN V151=.;                             
   IF V152 GE 0000008 OR V152=0000000 THEN V152=.;                             
   IF V153 GE 0000009 OR V153=0000000 THEN V153=.;                             
   IF V154 GE 0000009 OR V154=0000000 THEN V154=.;                             
   IF V155 GE 0000009 OR V155=0000000 THEN V155=.;                             
   IF V156 GE 0000009 OR V156=0000000 THEN V156=.;                             
   IF V157 GE 0000009 OR V157=0000000 THEN V157=.;                             
   IF V158 GE 0000008 OR V158=0000000 THEN V158=.;                             
   IF V159 GE 0000009 OR V159=0000000 THEN V159=.;                             
   IF V160 GE 0000091 THEN V160=.;                                             
   IF V161 GE 0000009 OR V161=0000000 THEN V161=.;                             
   IF V162 GE 0000008 OR V162=0000000 THEN V162=.;                             
   IF V163A=0000000 THEN V163A=.;      IF V163B=0000000 THEN V163B=.;          
   IF V163C=0000000 THEN V163C=.;      IF V164 GE 0000099 THEN V164=.;         
   IF V165 GE 0000009 THEN V165=.;                                             
   IF V166 GE 0009999 OR V166=0000000 THEN V166=.;                             
   IF V167 GE 0000098 THEN V167=.;                                             
   IF V168 GE 0000009 OR V168=0000000 THEN V168=.;                             
   IF V170 GE 0000098 THEN V170=.;     IF V171 GE 0000098 THEN V171=.;         
   IF V172 GE 0000098 THEN V172=.;     IF V173 GE 0000098 THEN V173=.;         
   IF V174 GE 0000098 THEN V174=.;     IF V175 GE 0000098 THEN V175=.;         
   IF V176 GE 0000009 OR V176=0000000 THEN V176=.;                             
   IF V179 GE 0000009 OR V179=0000000 THEN V179=.;                             
   IF V180 GE 0000009 OR V180=0000000 THEN V180=.;                             
   IF V182 GE 0000009 THEN V182=.;                                             
   IF V183 GE 0099999 OR V183=0000000 THEN V183=.;                             
   IF V184 GE 0000098 THEN V184=.;                                             
   IF V185 GE 0000999 OR V185=0000000 THEN V185=.;                             
   IF V186 GE 0009999 OR V186=0000000 THEN V186=.;                             
   IF V187 GE 0009999 OR V187=0000000 THEN V187=.;                             
   IF V188 GE 0000099 THEN V188=.;     IF V189 GE 0000009 THEN V189=.;         
   IF V190 GE 0000008 THEN V190=.;     IF V191 GE 0000008 THEN V191=.;         
   IF V192 GE 0000009 OR V192=0000000 THEN V192=.;                             
   IF V193 GE 0000009 THEN V193=.;     IF V194 GE 0000098 THEN V194=.;         
   IF V195 GE 0000009 OR V195=0000000 THEN V195=.;                             
   IF V196 GE 0000009 OR V196=0000000 THEN V196=.;                             
   IF V197 GE 0000091 THEN V197=.;                                             
   IF V198 GE 0099999 OR V198=0000000 THEN V198=.;                             
   IF V199 GE 0000009 THEN V199=.;                                             
   IF V200 GE 0000099 OR V200=0000000 THEN V200=.;                             
   IF V201 GE 0000009 OR V201=0000000 THEN V201=.;                             
   IF V202 GE 0000009 OR V202=0000000 THEN V202=.;                             
   IF V203 GE 0099999 OR V203=0000000 THEN V203=.;                             
   IF V204 GE 0099999 OR V204=0000000 THEN V204=.;                             
   IF V205 GE 0000091 THEN V205=.;                                             
   IF V206 GE 0000009 OR V206=0000000 THEN V206=.;                             
   IF V207 GE 0000008 THEN V207=.;                                             
   IF V208 GE 0099999 OR V208=0000000 THEN V208=.;                             
   IF V209 GE 0000095 OR V209=0000000 THEN V209=.;                             
   IF V210 GE 0099999 THEN V210=.;     IF V211 GE 0000098 THEN V211=.;         
   IF V212 GE 0099999 THEN V212=.;     IF V213 GE 0000098 THEN V213=.;         
   IF V214 GE 0000098 THEN V214=.;     IF V215 GE 0000098 THEN V215=.;         
   IF V216 GE 0000098 THEN V216=.;     IF V217 GE 0099999 THEN V217=.;         
   IF V218 GE 0000098 THEN V218=.;     IF V219 GE 0000098 THEN V219=.;         
   IF V220 GE 0000009 THEN V220=.;     IF V224 GE 0000009 THEN V224=.;         
   IF V227 GE 0000009 THEN V227=.;     IF V231 GE 0000098 THEN V231=.;         
   IF V232 GE 0000098 THEN V232=.;     IF V233 GE 0000098 THEN V233=.;         
   IF V234 GE 0000098 THEN V234=.;     IF V235 GE 0000098 THEN V235=.;         
   IF V236A GE 0000008 OR V236A=0000000 THEN V236A=.;                          
   IF V236B GE 0000008 OR V236B=0000000 THEN V236B=.;                          
   IF V237A GE 0000008 OR V237A=0000000 THEN V237A=.;                          
   IF V237B GE 0000008 OR V237B=0000000 THEN V237B=.;                          
   IF V238A GE 0000099 OR V238A=0000000 THEN V238A=.;                          
   IF V238B GE 0000099 OR V238B=0000000 THEN V238B=.;                          
   IF V239 GE 0000009 OR V239=0000000 THEN V239=.;                             
   IF V240 GE 0000009 THEN V240=.;     IF V241 GE 0000009 THEN V241=.;         
   IF V242 GE 0000099 THEN V242=.;     IF V243 GE 0000009 THEN V243=.;         
   IF V244 GE 0000009 THEN V244=.;                                             
   IF V245 GE 0000009 OR V245=0000000 THEN V245=.;                             
   IF V246 GE 0000009 OR V246=0000000 THEN V246=.;                             
   IF V249 GE 0000009 OR V249=0000000 THEN V249=.;                             
   IF V252 GE 0000009 OR V252=0000000 THEN V252=.;                             
   IF V255 GE 0099999 THEN V255=.;     IF V256 GE 0000008 THEN V256=.;         
   IF V257 GE 0099999 THEN V257=.;     IF V258 GE 0000008 THEN V258=.;         
   IF V259 GE 0099999 THEN V259=.;     IF V260 GE 0000008 THEN V260=.;         
   IF V261 GE 0099999 THEN V261=.;     IF V262 GE 0000008 THEN V262=.;         
   IF V263 GE 0000009 OR V263=0000000 THEN V263=.;                             
   IF V266 GE 0000009 OR V266=0000000 THEN V266=.;                             
   IF V269 GE 0000999 OR V269=0000000 THEN V269=.;                             
   IF V270 GE 0000098 THEN V270=.;     IF V272 GE 0000009 THEN V272=.;         
   IF V273 GE 0099999 OR V273=0000000 THEN V273=.;                             
   IF V274 GE 0000098 THEN V274=.;                                             
   IF V275 GE 0000009 OR V275=0000000 THEN V275=.;                             
   IF V276 GE 0099999 OR V276=0000000 THEN V276=.;                             
   IF V277 GE 0000009 OR V277=0000000 THEN V277=.;                             
   IF V278 GE 0000098 THEN V278=.;                                             
   IF V279 GE 0099999 OR V279=0000000 THEN V279=.;                             
   IF V280 GE 0000098 THEN V280=.;                                             
   IF V281 GE 0099999 OR V281=0000000 THEN V281=.;                             
   IF V282 GE 0000098 THEN V282=.;                                             
   IF V283 GE 0000009 OR V283=0000000 THEN V283=.;                             
   IF V284 GE 0099999 OR V284=0000000 THEN V284=.;                             
   IF V285 GE 0000009 OR V285=0000000 THEN V285=.;                             
   IF V286 GE 0000098 THEN V286=.;     IF V287 GE 0000009 THEN V287=.;         
   IF V288 GE 0000009 THEN V288=.;                                             
   IF V289 GE 0000008 OR V289=0000000 THEN V289=.;                             
   IF V290 GE 0000099 THEN V290=.;     IF V291 GE 0000009 THEN V291=.;         
   IF V292 GE 0000009 THEN V292=.;     IF V293 GE 0000009 THEN V293=.;         
   IF V294 GE 0000009 THEN V294=.;     IF V295 GE 0000009 THEN V295=.;         
   IF V297 GE 0000009 THEN V297=.;     IF V298=0000000 THEN V298=.;            
   IF V299 GE 0000099 THEN V299=.;     IF V300 GE 0000095 THEN V300=.;         
   IF V301=0000000 THEN V301=.;        IF V302=000000. THEN V302=.;            
   IF V303=000000. THEN V303=.;        IF V304 GE 0000091 THEN V304=.;         
   IF V305 GE 0000091 THEN V305=.;                                             
   IF V306 GE 0000999 OR V306=0000000 THEN V306=.;                             
   IF V307 GE 0000098 THEN V307=.;                                             
   IF V308A GE 0000095 OR V308A=0000000 THEN V308A=.;                          
   IF V308B GE 0000095 OR V308B=0000000 THEN V308B=.;                          
   IF V309 GE 0009999 OR V309=0000000 THEN V309=.;                             
   IF V310 GE 0000008 OR V310=0000000 THEN V310=.;                             
   IF V311 GE 0000009 OR V311=0000000 THEN V311=.;                             
   IF V312 GE 0099999 THEN V312=.;     IF V313 GE 0000098 THEN V313=.;         
   IF V314 GE 0000009 THEN V314=.;     IF V315 GE 0999999 THEN V315=.;         
   IF V316 GE 0000009 THEN V316=.;     IF V317 GE 0000009 THEN V317=.;         
   IF V318 GE 0000099 THEN V318=.;     IF V319 GE 0000009 THEN V319=.;         
   IF V320 GE 0999999 THEN V320=.;     IF V321 GE 0000009 THEN V321=.;         
   IF V322 GE 0000009 THEN V322=.;     IF V323 GE 0000009 THEN V323=.;         
   IF V324=0000000 THEN V324=.;                                                
   IF V325 GE 0000009 OR V325=0000000 THEN V325=.;                             
   IF V326 GE 0000009 OR V326=0000000 THEN V326=.;                             
   IF V327 GE 0000009 OR V327=0000000 THEN V327=.;                             
   IF V328 GE 0000009 THEN V328=.;     IF V329 GE 0999999 THEN V329=.;         
   IF V330 GE 0000009 THEN V330=.;     IF V331 GE 0000009 THEN V331=.;         
   IF V332=0000000 THEN V332=.;                                                
*/                                                                             
