/*                                                                             
               SAS DATA DEFINITION STATEMENTS FOR ICPSR 7443                   
                    SURVEY OF CONSUMER FINANCES, 1963                          
                          NOVEMBER 1977 VERSION                                
                                                                               
   The following SAS setup sections may appear in this file for the LRECL      
   version of this data collection.  These sections are listed below:          
                                                                               
   PROC FORMAT, in these statements, creates user-defined labels as            
   formats for variable values.   Formats replace original values with the     
   user-defined labels in subsequent SAS procedures once the formats           
   are assigned to a variable by the FORMAT command in the DATA step.          
   Not all variables necessarily have user-defined formats.                    
                                                                               
   DATA begins a SAS data step and names an output SAS dataset.                
                                                                               
   INFILE identifies the input file to be read with the input statement.       
   Users must replace the "file-specification" with host computer-specific     
   input file specifications.                                                  
                                                                               
   INPUT contains the SAS statements which assign the variable names and       
   specify the beginning and ending column locations in the LRECL data         
   file for each variable.                                                     
                                                                               
   LABEL assigns variable labels for all variables in the data file.           
   Variable labels and variable names may be identical for some data           
   files.                                                                      
                                                                               
   FORMAT in the SAS data step assigns the formats generated by the            
   PROC FORMAT procedure with the variable values in the SAS system file.      
   When SAS subsequently creates output, it utilizes the labels                
   found in the FORMAT rather than the raw data values.  NOTE: If a format     
   is assigned to a variable with a FORMAT statement, the values for           
   the variable are categorized by their labels *before* compilation and       
   printing by subsequent SAS procedures, i.e., values with identical          
   formats are treated as one group even though their values are               
   different.  Accordingly, users need to look at variable values before       
   jobs are run to assure that inadvertent grouping of results does not        
   occur.                                                                      
                                                                               
   MISSING VALUE RECODE sets user-defined numeric missing values to            
   missing as interpreted by the SAS system.  Only variables with              
   user-defined missing values are included in these statements.               
                                                                               
   Users may combine and modify these sections or parts of these sections      
   to suit their specific needs.  Users will also need to change the           
   file-specification in the INFILE statement to an appropriate filename       
   for their system.  Please note that the PROC FORMAT, FORMAT and             
   MISSING VALUE RECODE sections have been commented out (i.e., '/*').         
   To include the PROC FORMAT, FORMAT and MISSING VALUE RECODE sections        
   in the final SAS setup, remove the comment indicators from those            
   sections.                                                                   
                                                                               
**************************************************************************** */
                                                                               
* SAS DATA, INFILE, INPUT STATEMENTS;                                          
                                                                               
DATA;                                                                          
INFILE "file-specification" LRECL=961;                                         
INPUT                                                                          
   V1 1-3                   V2 4-7                   V3 8-8                    
   V4 9-9                   V5 10-15                 V6 16-16                  
   V7 17-17                 V8 18-23                 V9 24-24                  
   V10 25-25                V11 26-26                V12 27-27                 
   V13 28-28                V14 29-29                V15 30-30                 
   V16 31-31                V17 32-32                V18 33-38                 
   V19 39-39                V20 40-45                V21 46-46                 
   V22 47-47                V23 48-53                V24 54-54                 
   V25 55-55                V26 56-56                V27 57-57                 
   V28 58-58                V29 59-59                V30 60-60                 
   V31 61-61                V32 62-62                V33 63-63                 
   V34 64-64                V35 65-66                V36 67-67                 
   V37 68-69                V38 70-70                V39 71-71                 
   V40 72-72                V41 73-73                V42 74-74                 
   V43 75-75                V44 76-76                V45 77-81                 
   V46 82-83                V47 84-84                V48 85-85                 
   V49 86-87                V50 88-89                V51 $ 90-92               
   V52 93-94                V53 95-96                V54 97-97                 
   V55 98-99                V56 100-100              V57 101-102               
   V58 103-103              V59 104-104              V60 105-105               
   V61 106-106              V62 107-107              V63 108-108               
   V64 109-109              V65 110-110              V66 111-111               
   V67 112-112              V68 113-113              V69 114-114               
   V70 115-115              V71 116-116              V72 117-117               
   V73 118-118              V74 119-119              V75 120-120               
   V76 121-121              V77 122-122              V78 123-123               
   V79 124-125              V80 126-127              V81 128-129               
   V82 130-131              V83 132-132              V84 133-133               
   V85 134-134              V86 135-136              V87 137-137               
   V88 138-139              V89 140-140              V90 141-142               
   V91 143-143              V92 144-145              V93 146-147               
   V94 148-149              V95 150-150              V96 151-156               
   V97 157-157              V98 158-158              V99 159-160               
   V100 161-161             V101 162-163             V102 164-164              
   V103 165-165             V104 166-166             V105 167-169              
   V106 170-170             V107 171-176             V108 177-178              
   V109 179-179             V110 180-180             V111 181-181              
   V112 182-186             V113 187-187             V114 188-190              
   V115 191-191             V116 192-194             V117 195-195              
   V118 196-197             V119 198-198             V120 199-199              
   V121 200-203             V122 204-204             V123 205-205              
   V124 206-210             V125 211-211             V126 212-212              
   V127 213-213             V128 214-214             V129 215-215              
   V130 216-221             V131 222-222             V132 223-223              
   V133 224-224             V134 225-225             V135 226-227              
   V136 228-229             V137 230-231             V138 232-232              
   V139 233-233             V140 234-234             V141 235-235              
   V142 236-237             V143 238-238             V144 239-240              
   V145 241-241             V146 242-243             V147 244-245              
   V148 246-246             V149 247-247             V150 248-249              
   V151 250-250             V152 251-251             V153 252-253              
   V154 254-255             V155 256-256             V156 257-258              
   V157 259-259             V158 260-263             V159 264-265              
   V160 266-269             V161 270-271             V162 272-275              
   V163 276-277             V164 278-281             V165 282-282              
   V166 283-286             V167 287-287             V168 288-291              
   V169 292-292             V170 293-293             V171 294-296              
   V172 297-297             V173 298-299             V174 300-301              
   V175 302-302             V176 303-303             V177 304-304              
   V178 305-305             V179 306-306             V180 307-307              
   V181 308-308             V182 309-309             V183 310-310              
   V184 311-311             V185 312-312             V186 313-314              
   V187 315-318             V188 319-319             V189 320-323              
   V190 324-324             V191 325-328             V192 329-329              
   V193 330-330             V194 331-331             V195 332-332              
   V196 333-333             V197 334-334             V198 335-335              
   V199 336-336             V200 337-337             V201 338-338              
   V202 339-339             V203 340-340             V204 341-341              
   V205 342-342             V206 343-343             V207 344-344              
   V208 345-345             V209 346-349             V210 350-350              
   V211 351-354             V212 355-356             V213 357-361              
   V214 362-362             V215 363-366             V216 367-368              
   V217 369-373             V218 374-375             V219 376-376              
   V220 377-377             V221 378-378             V222 379-380              
   V223 381-381             V224 382-383             V225 384-384              
   V226 385-385             V227 386-386             V228 387-387              
   V229 388-389             V230 390-390             V231 391-394              
   V232 395-398             V233 399-402             V234 403-406              
   V235 407-409             V236 410-413             V237 414-417              
   V238 418-418             V239 419-419             V240 420-420              
   V241 421-421             V242 422-422             V243 423-423              
   V244 424-424             V245 425-425             V246 426-426              
   V247 427-427             V248 428-428             V249 429-429              
   V250 430-430             V251 431-431             V252 432-435              
   V253 436-436             V254 437-442             V255 443-444              
   V256 445-447             V257 448-448             V258 449-453              
   V259 454-458             V260 459-463             V261 464-468              
   V262 469-474             V263 475-479             V264 480-485              
   V265 486-487             V266 488-489             V267 490-491              
   V268 492-493             V269 494-495             V270 496-496              
   V271 497-497             V272 498-498             V273 499-499              
   V274 500-500             V275 501-501             V276 502-506              
   V277 507-507             V278 508-508             V279 509-509              
   V280 510-510             V281 511-511             V282 512-512              
   V283 513-513             V284 514-514             V285 515-515              
   V286 516-516             V287 517-518             V288 519-520              
   V289 521-521             V290 522-522             V291 523-523              
   V292 524-524             V293 525-526             V294 527-528              
   V295 529-529             V296 530-530             V297 531-531              
   V298 532-532             V299 533-533             V300 534-534              
   V301 535-535             V302 536-536             V303 537-541              
   V304 542-542             V305 543-547             V306 548-548              
   V307 549-549             V308 550-550             V309 551-552              
   V310 553-553             V311 554-554             V312 555-560              
   V313 561-561             V314 562-567             V315 568-568              
   V316 569-569             V317 570-575             V318 576-576              
   V319 577-577             V320 578-579             V321 580-581              
   V322 582-583             V323 584-584             V324 585-585              
   V325 586-586             V326 587-587             V327 588-589              
   V328 590-590             V329 591-591             V330 592-592              
   V331 593-593             V332 594-597             V333 598-598              
   V334 599-599             V335 600-600             V336 601-601              
   V337 602-607             V338 608-608             V339 609-609              
   V340 610-615             V341 616-616             V342 617-622              
   V343 623-623             V344 624-624             V345 625-630              
   V346 631-631             V347 632-632             V348 633-633              
   V349 634-634             V350 635-635             V351 636-636              
   V352 637-637             V353 638-639             V354 640-640              
   V355 641-642             V356 643-644             V357 645-645              
   V358 646-647             V359 648-648             V360 649-649              
   V361 650-650             V362 651-652             V363 653-654              
   V364 655-655             V365 656-656             V366 657-657              
   V367 658-659             V368 660-661             V369 662-662              
   V370 663-663             V371 664-665             V372 666-667              
   V373 668-668             V374 669-670             V375 671-672              
   V376 673-673             V377 674-675             V378 676-677              
   V379 678-678             V380 679-679             V381 680-680              
   V382 681-681             V383 682-682             V384 683-683              
   V385 684-684             V386 685-685             V387 686-686              
   V388 687-687             V389 688-688             V390 689-689              
   V391 690-691             V392 692-693             V393 694-694              
   V394 695-696             V395 697-698             V396 699-699              
   V397 700-700             V398 701-701             V399 702-702              
   V400 703-703             V401 704-705             V402 706-707              
   V403 708-708             V404 709-709             V405 710-710              
   V406 711-711             V407 712-712             V408 713-714              
   V409 715-715             V410 716-716             V411 717-717              
   V412 718-721             V413 722-722             V414 723-723              
   V415 724-725             V416 726-727             V417 728-728              
   V418 729-732             V419 733-733             V420 734-735              
   V421 736-736             V422 737-738             V423 739-739              
   V424 740-741             V425 742-742             V426 743-744              
   V427 745-745             V428 746-746             V429 747-748              
   V430 749-749             V431 750-751             V432 752-752              
   V433 753-754             V434 755-755             V435 756-761              
   V436 762-767             V437 768-773             V438 774-775              
   V439 776-777             V440 778-779             V441 780-785              
   V442 786-786             V443 787-792             V444 793-798              
   V445 799-804             V446 805-810             V447 811-816              
   V448 817-820             V449 821-824             V450 825-825              
   V451 826-826             V452 827-827             V453 828-828              
   V454 829-829             V455 830-830             V456 831-831              
   V457 832-832             V458 833-838             V459 839-844              
   V460 845-850             V461 851-856             V462 857-862              
   V463 863-868             V464 869-874             V465 875-880              
   V466 881-886             V467 887-889             V468 890-892              
   V469 893-893             V470 894-894             V471 895-895              
   V472 896-896             V473 897-897             V474 898-898              
   V475 899-899             V476 900-900             V477 901-906              
   V478 907-910             V479 911-916             V480 917-922              
   V481 923-928             V482 929-934             V483 935-940              
   V484 941-946             V485 947-948             V486 949-950              
   V487 951-951             V488 952-952             V489 953-953              
   V490 954-954             V491 955-955             V492 956-956              
   V493 957-958             V494 959-959             V495 960-961;             
                                                                               
* SAS LABEL STATEMENT;                                                         
                                                                               
LABEL                                                                          
   V1 = "STUDY NO(717)"                                                        
   V2 = "INTV NO"                                                              
   V3 = "QJ9 OWN STOCK"                                                        
   V4 = "QJ10 PRIV/GEN STOCK"                                                  
   V5 = "QJ11$STK WITH (PUB)"                                                  
   V6 = "QJ11 BKT STK WTH(PUB)"                                                
   V7 = "QJ11 BKT (PRV)STK WTH"                                                
   V8 = "QJ11 $TOT STK"                                                        
   V9 = "QJ11 BKT TOT STK"                                                     
   V10 = "QJ12 MON IN/OUT STK"                                                 
   V11 = "QJ13 HOW MUCH I/O STK"                                               
   V12 = "QJ9,10 ASSGN STK"                                                    
   V13 = "QJ14A-H GOVT BONDS"                                                  
   V14 = "QJ14B ST/LOC BONDS"                                                  
   V15 = "QJ14C CORP BONDS"                                                    
   V16 = "QJ14D OTH REAL EST R1"                                               
   V17 = "QJ14D OTH REAL EST R2"                                               
   V18 = "QJ14F $GROSS AMT"                                                    
   V19 = "QJ14F BKT GROSS AMT"                                                 
   V20 = "QJ14F $NET AMT"                                                      
   V21 = "QJ14F BKT NET AMT"                                                   
   V22 = "QJ14H MORT/LD CONT AMT"                                              
   V23 = "$TOT OTH ASSETS"                                                     
   V24 = "BKT TOT OTH ASSETS"                                                  
   V25 = "QJ14A-D,H ASSGN OTH INVT"                                            
   V26 = "QJ15 FIN COMP 2 YRS AGO"                                             
   V27 = "QJ16,J17 WHEN ACM ASSETS"                                            
   V28 = "QJ18 REC INHERIT"                                                    
   V29 = "J19 REC LIFE INS POL"                                                
   V30 = "QJ20 ASSETS INH/SAV"                                                 
   V31 = "BRK AMT INH"                                                         
   V32 = "QJ21-J22 LEAVE HEIRS"                                                
   V33 = "QJ22A WHO HEIRS"                                                     
   V34 = "QJ22B HOW MUCH INH"                                                  
   V35 = "TOT SU INC"                                                          
   V36 = "AGE HD SU"                                                           
   V37 = "LIFE CYCLE"                                                          
   V38 = "QL4-C EDUC HD SU"                                                    
   V39 = "QA14-A PRCS HGH/LWR"                                                 
   V40 = "QA6 EARNS UP/DWN"                                                    
   V41 = "QG1 HD EMPL/UNEMPL"                                                  
   V42 = "QG4 WRK SELF/OTH"                                                    
   V43 = "QG6 WKS FULL TIME"                                                   
   V44 = "EMP STAT"                                                            
   V45 = "SAMPLE NO"                                                           
   V46 = "SECOND SELEC"                                                        
   V47 = "BELT"                                                                
   V48 = "SIZE"                                                                
   V49 = "DISTANCE"                                                            
   V50 = "SU COMP"                                                             
   V51 = "INTRV NO"                                                            
   V52 = "INTERVIEWER'S INT NO."                                               
   V53 = "WEEK OF INTERVIEW"                                                   
   V54 = "SEX OF HEAD"                                                         
   V55 = "AGE HD SU (ACT AGE)"                                                 
   V56 = "AGE HD SU (ASSGN)"                                                   
   V57 = "AGE WIFE HD (ACT AGE)"                                               
   V58 = "AGE WIFE HD (ASSGN)"                                                 
   V59 = "IS R HD OF SU"                                                       
   V60 = "SEX OF R"                                                            
   V61 = "NO ADULTS SU"                                                        
   V62 = "ANYO OVER 65"                                                        
   V63 = "Q3,3A NO CHILD U 18"                                                 
   V64 = "Q36 OLDEST UND 18"                                                   
   V65 = "Q3B OLD CHILD UND 18"                                                
   V66 = "TOT NO IN SU"                                                        
   V67 = "Q4-A NO CHILD NOT LIV SU"                                            
   V68 = "Q4-B CHILD OV/18 NT SU"                                              
   V69 = "QL1 OTH DEPNDS"                                                      
   V70 = "QL2 HD MRD/SNGL"                                                     
   V71 = "QL3 LGTH MARR"                                                       
   V72 = "QL4-C EDUC HD SU"                                                    
   V73 = "QL4-C EDUC WIFE HD SU"                                               
   V74 = "QN3 RACE"                                                            
   V75 = "QN4 LGTH INTV"                                                       
   V76 = "QN5 NO CALLS"                                                        
   V77 = "QN6 PRES DUR INTV"                                                   
   V78 = "QN7 TYPE STRUCT"                                                     
   V79 = "QN8 DESCRP NGHBH R1"                                                 
   V80 = "QN8 DSCRP NGHBH R2"                                                  
   V81 = "QN8 DSCRP NGHBH R3"                                                  
   V82 = "CODER NO"                                                            
   V83 = "QK2,K8 DATE BIRTH"                                                   
   V84 = "REGION"                                                              
   V85 = "LIFE CYCLE GM"                                                       
   V86 = "LIFE CYCLE"                                                          
   V87 = "EDUC HD"                                                             
   V88 = "SU INC"                                                              
   V89 = "SU INC (COLPSD)"                                                     
   V90 = "SU TOT INC DCLS"                                                     
   V91 = "SU TOT INC QUINTLS"                                                  
   V92 = "OCCUP A UNEM SEP"                                                    
   V93 = "OCCUP B UNEM CLASS"                                                  
   V94 = "EXTENT UNEMPL"                                                       
   V95 = "INCOME CHANGE"                                                       
   V96 = "TOT SU INC"                                                          
   V97 = "COMMERC NGHBH"                                                       
   V98 = "FAM MTCH IDENT"                                                      
   V99 = "CHARACT NGHBH"                                                       
   V100 = "SU COMP"                                                            
   V101 = "QB1 WHEN MOVE"                                                      
   V102 = "QB2 WHAT YR MOVE"                                                   
   V103 = "QB3 OWN/RENT"                                                       
   V104 = "QB4 WHY NEITHER"                                                    
   V105 = "QB5 $AMT RENT MTH"                                                  
   V106 = "BKT MTH RENT"                                                       
   V107 = "QB6,B9$VALUE HOUSE"                                                 
   V108 = "QB6,B9 BKT VAL HOUSE"                                               
   V109 = "QB7,8A WHEN BUILT"                                                  
   V110 = "QB8 NEW/OLD HS"                                                     
   V111 = "QB10,11 MORT/SEC MORT"                                              
   V112 = "QB12 $AMT MORT"                                                     
   V113 = "QB12 BKT AMT HS MORT"                                               
   V114 = "QB13 $AMT HS PYMTS"                                                 
   V115 = "QB13 BKT MTH MORT PYMTS"                                            
   V116 = "QB14 $AMT TO PRINCPL"                                               
   V117 = "QB14 BKT TOT MTH PRIN PY"                                           
   V118 = "QB15 NO YRS REPAY MORT"                                             
   V119 = "QB12 AMT SEC MORT"                                                  
   V120 = "ASSGN HS VAL/MORT"                                                  
   V121 = "$ EXP ON ADD"                                                       
   V122 = "BKT EXP ON ADD"                                                     
   V123 = "BKT EXP ON REPAIRS"                                                 
   V124 = "$TOT EXP ADD/RPRS"                                                  
   V125 = "BKT TOT EXP ADD/RPRS"                                               
   V126 = "ASSGN ADD/RPRS"                                                     
   V127 = "HS STAT"                                                            
   V128 = "1962 HS PURCH"                                                      
   V129 = "HS STAT/DUR"                                                        
   V130 = "$HS EQUITY"                                                         
   V131 = "BKT HS EQUITY"                                                      
   V132 = "GM INC QTLS"                                                        
   V133 = "GM LIFE CYCLE"                                                      
   V134 = "AGE SU HD"                                                          
   V135 = "OCCUP A"                                                            
   V136 = "SU INC"                                                             
   V137 = "LIFE CYCLE"                                                         
   V138 = "TYPE STRUC"                                                         
   V139 = "1960 CENSUS-BELT"                                                   
   V140 = "RAT ANN INSTAL DEBT"                                                
   V141 = "TOT REM INSTAL DEBT"                                                
   V142 = "TOT FAM INC"                                                        
   V143 = "FARM FAM"                                                           
   V144 = "TOT CARS SU"                                                        
   V145 = "QC4 FIRST CAR N/U"                                                  
   V146 = "QC5 WHAT MAKE"                                                      
   V147 = "QC5 YEAR MODEL"                                                     
   V148 = "QC5,6 TYPE CAR"                                                     
   V149 = "QC6A COMPCT/REG-SZ"                                                 
   V150 = "QC7 WHAT YR BUY"                                                    
   V151 = "QC8 WHO BUY FROM"                                                   
   V152 = "QC9 TRDE-IN/SELL"                                                   
   V153 = "QC10 MAKE TRDE-IN/SELL"                                             
   V154 = "QC10 YR MODEL"                                                      
   V155 = "QC10,11 TYPE TRDE-IN/SEL"                                           
   V156 = "QC12 WHAT YR BUY"                                                   
   V157 = "QC14-16 FINAN ARRNGM"                                               
   V158 = "QC13$TOT PRC 1ST CAR"                                               
   V159 = "QC13 BKT TOT PRC"                                                   
   V160 = "QC14 $AMT FR TRD-IN/SEL"                                            
   V161 = "QC14 BKT AMT FR T-I/SALE"                                           
   V162 = "$NET OUTLAY 1ST CAR"                                                
   V163 = "BKT NET OUTLAY 1ST CAR"                                             
   V164 = "QC15 $PAID IN CASH"                                                 
   V165 = "QC15 BKT PAID IN CASH"                                              
   V166 = "QC16 $AMT BORW/FINANC"                                              
   V167 = "QC16 BKT AMT BORW/FINANC"                                           
   V168 = "$INSTAL DEBT"                                                       
   V169 = "BKT INSTAL DEBT"                                                    
   V170 = "QC23 BORW/OWES 1ST CAR"                                             
   V171 = "QC24 $AMT PAYM MTH"                                                 
   V172 = "QC24 BKT AMT MTH PAYM"                                              
   V173 = "QC18 ORIG LGTH DEBT"                                                
   V174 = "QC20 AMT PAYMS LEFT"                                                
   V175 = "QC22,26 TOT REMN DEBT"                                              
   V176 = "REMN INSTALL DEBT"                                                  
   V177 = "Q27 OTH CAR 62"                                                     
   V178 = "1962-63 CAR PURCH"                                                  
   V179 = "1962 CREDIT-PURCH"                                                  
   V180 = "SPECIAL OWNSHP CODE"                                                
   V181 = "SPECIAL TYPE CAR"                                                   
   V182 = "AGE RANK CARS OWND SU"                                              
   V183 = "SU TOT INC QNTLS"                                                   
   V184 = "LIFE CYCLE"                                                         
   V185 = "AGE HEAD SU"                                                        
   V186 = "SU INCOME"                                                          
   V187 = "QD1-3 $TOT PRC DURB GOOD"                                           
   V188 = "QD1-3 BKT PRC DURB GOODS"                                           
   V189 = "QD4-5 $AMT TRD-I/SALES"                                             
   V190 = "QD4-5 BKT AMT TRD-I/SALE"                                           
   V191 = "$TOT NET OUTLAY"                                                    
   V192 = "BKT TOT NET OUTLAY"                                                 
   V193 = "PURCH TELE"                                                         
   V194 = "REFRIG"                                                             
   V195 = "WASH MACH"                                                          
   V196 = "STOVE/RANGE"                                                        
   V197 = "FURNITURE"                                                          
   V198 = "CLOTHES DRYER"                                                      
   V199 = "DISHWASHER"                                                         
   V200 = "AIR CONDITIONER"                                                    
   V201 = "OTH PURCHASES R1"                                                   
   V202 = "OTH PURCHASES R2"                                                   
   V203 = "QD6 BUY CRDT/CASH"                                                  
   V204 = "QD16 VACATION 62"                                                   
   V205 = "QD17 SPND ON VACAT"                                                 
   V206 = "QD18 NO VACAT IN YR"                                                
   V207 = "QD19 HOW FAR"                                                       
   V208 = "QD20 $AMT SPND ALTOG"                                               
   V209 = "QD20 $TOT VACT EXP"                                                 
   V210 = "QD20 BKT TOT VACAT EXP"                                             
   V211 = "$TOT NET OUTLAY CARS"                                               
   V212 = "BKT TOT NET OTLY CARS"                                              
   V213 = "$TOT EXP ADD/RPRS"                                                  
   V214 = "BKT TOT EXP ADD/RPRS"                                               
   V215 = "$NET OUTLY CARS/DRBLS"                                              
   V216 = "BKT NET OUTLY CARS/DRBLS"                                           
   V217 = "$NET OTLY CRS/DUR/A AND R"                                          
   V218 = "BKT NET OTLY CRS/DUR/A AND R"                                       
   V219 = "SU TOT INC QNTLS"                                                   
   V220 = "LIFE CYCLE GM"                                                      
   V221 = "AGE HD SU"                                                          
   V222 = "LIFE CYCLE"                                                         
   V223 = "QN7 TYPE STRUCT"                                                    
   V224 = "SU INC"                                                             
   V225 = "INC CHANGE"                                                         
   V226 = "EDUC OF HD"                                                         
   V227 = "RACE"                                                               
   V228 = "SIZE PLACE"                                                         
   V229 = "OCCUP B"                                                            
   V230 = "REGION"                                                             
   V231 = "$ REM INSTAL DBT ADD/RPR"                                           
   V232 = "$REM INSTAL DBT CARS"                                               
   V233 = "$REM INSTAL DBT OTH DRBL"                                           
   V234 = "$REM OTH INSTAL DEBT"                                               
   V235 = "$TOT MTH PAYMTS"                                                    
   V236 = "$TOT REM INSTAL DBT"                                                
   V237 = "$REM TOT DEBT"                                                      
   V238 = "BKT TOT MTH PAYM RATE"                                              
   V239 = "BKT REM INSTAL DBT A AND R"                                         
   V240 = "BKT INSTAL DBT CARS"                                                
   V241 = "BKT RID OTHER DUR"                                                  
   V242 = "BKT REM OTH INSTAL DBT"                                             
   V243 = "BKT TOT REM INSTAL DEBT"                                            
   V244 = "BKT REM TOT DBT A+R"                                                
   V245 = "BKT REM TOT DBT CARS"                                               
   V246 = "BKT REM TOT DBT OTH DUR"                                            
   V247 = "BKT REM TOT OTH DEBT"                                               
   V248 = "BKT REM TOT DEBT"                                                   
   V249 = "BKT MEDICAL DEBT DR"                                                
   V250 = "BKT MED DEBT-DENT"                                                  
   V251 = "BKT MED DEBT-HOSP"                                                  
   V252 = "$TOT MED DEBT"                                                      
   V253 = "BKT TOT MED DEBT"                                                   
   V254 = "SU DISP INC"                                                        
   V255 = "DIS INCOME"                                                         
   V256 = "$RATIO AIDP/DISP INC"                                               
   V257 = "BKT AIDP/DISP INC"                                                  
   V258 = "SU WAGE/SAL INC"                                                    
   V259 = "MIX LAB-CAP INC"                                                    
   V260 = "CAP INC"                                                            
   V261 = "TRANS PAY"                                                          
   V262 = "TOT SU INC $"                                                       
   V263 = "TOT INC TAX"                                                        
   V264 = "SU DISP INC"                                                        
   V265 = "BKT TOT SU INC"                                                     
   V266 = "BKT TOT INC TAX"                                                    
   V267 = "BKT TOT DISP INC"                                                   
   V268 = "BKT H AND W GROSS TAX INC"                                          
   V269 = "BKT OTH GROSS TAX INC"                                              
   V270 = "SU WAGE/SAL SUBT A"                                                 
   V271 = "INC FARMING"                                                        
   V272 = "ROOMER/BOARD INC"                                                   
   V273 = "MIX LAB-CAP INS SUBT B"                                             
   V274 = "CAP INC-RT  SUBT C"                                                 
   V275 = "TRANS PAYM  SUBT D"                                                 
   V276 = "$ HD EARNED INC"                                                    
   V277 = "BKT HD EARNED INC"                                                  
   V278 = "WF WAGE/SAL INC"                                                    
   V279 = "HD TOT INC"                                                         
   V280 = "WF TOT INC"                                                         
   V281 = "OTH TOT INC"                                                        
   V282 = "NO MEMB INC SUBT A AND B"                                           
   V283 = "PROP TOT INC REC WF"                                                
   V284 = "TYPE TRANSF INC R1"                                                 
   V285 = "TYPE TRANSF INC R2"                                                 
   V286 = "ANY INC ASSGNM"                                                     
   V287 = "SU TOT INC DCLS"                                                    
   V288 = "SU DISP INC DCLS"                                                   
   V289 = "AGE-EDUC"                                                           
   V290 = "QG1 WORK/UNEMP/ETC"                                                 
   V291 = "QG1A TIME SINCE WK FL-T"                                            
   V292 = "QG1B EVER WORK FUL-T"                                               
   V293 = "QG2 HD OCCUP"                                                       
   V294 = "QG3 KIND OF BUSS"                                                   
   V295 = "QG4 WORK SELF/SOME ELSE"                                            
   V296 = "QG5 EMPLOY OTHERS"                                                  
   V297 = "QG6 WKS WRK FL-T/PD VAC"                                            
   V298 = "QG6,7 NO FL-T/PT-T"                                                 
   V299 = "QG8,9 REASONS NOT WRK R1"                                           
   V300 = "QG8,9 REAS NOT WORK R2"                                             
   V301 = "QG10 1961 WORK LESS?"                                               
   V302 = "QG11 HD 2ND JOB"                                                    
   V303 = "QG14$NET FARM INC SU"                                               
   V304 = "QG14 BKT NET FARM INC SU"                                           
   V305 = "QG17 $MARKET VAL LVST"                                              
   V306 = "QG17 BKT MARKET VAL LVST"                                           
   V307 = "QG18 OWE MONEY LVST"                                                
   V308 = "QG21 OWN BUSS/FIN INT"                                              
   V309 = "QG22 SORT OF BUSS"                                                  
   V310 = "QG23 SOLE OWN/PARTSHP"                                              
   V311 = "QG24 CORP/UNINCORP"                                                 
   V312 = "QG26-34$TOT LOSS/PROFIT"                                            
   V313 = "QG26-34 BKT TOT LOSS/PRO"                                           
   V314 = "QG35 $SHARE BUS WORTH"                                              
   V315 = "QG35 BKT SHARE BUS WORT"                                            
   V316 = "QG49 INC LRG/SML"                                                   
   V317 = "QG50 $INC SU LAST YR"                                               
   V318 = "QG50 BKT INC SU LAST YR"                                            
   V319 = "BKT RAT 62/61 SU INC"                                               
   V320 = "OCCUP A UNEMPL SEP"                                                 
   V321 = "OCCUP B UNEMPL"                                                     
   V322 = "EXTENT OF EMPLOY"                                                   
   V323 = "INCOME CHANGE"                                                      
   V324 = "RACE"                                                               
   V325 = "AGE-EDUC"                                                           
   V326 = "REGION"                                                             
   V327 = "SU TOT INC DCLS"                                                    
   V328 = "HD EARN INC"                                                        
   V329 = "NO MAJOR EARNERS"                                                   
   V330 = "OCCUP-REGROUPED"                                                    
   V331 = "QJ1 LIFE INS"                                                       
   V332 = "QJ1A $AMT IN LIFE INS PR"                                           
   V333 = "QJ1A BKT TOT PREMIUM PAY"                                           
   V334 = "QJ2 OWE ON POLC LOAN"                                               
   V335 = "QJ3 ANY NEW POLCY 62"                                               
   V336 = "QJ1,3 ASSGNM LIFE INS"                                              
   V337 = "$US SAV BONDS"                                                      
   V338 = "BKT US SAV BONDS"                                                   
   V339 = "QJ5,A SAV ACCTS HOLD"                                               
   V340 = "$TOT SAV ACCTS"                                                     
   V341 = "BKT TOT SAV ACCTS"                                                  
   V342 = "$TOT CHECK ACCTS"                                                   
   V343 = "BKT TOT CHECK ACCTS"                                                
   V344 = "PATT LIQ ASSET HOLD"                                                
   V345 = "$TOT LIQ ASSET"                                                     
   V346 = "BKT TOT LIQ ASSET"                                                  
   V347 = "ASSGNM REQ-LIQ ASSET"                                               
   V348 = "ASSGNM SAV ACCTS"                                                   
   V349 = "QJ8 MORE/LESS LAST YR"                                              
   V350 = "QJ8A BKT AMT MORE/LESS"                                             
   V351 = "QJ12 MON IN/OUT STOCK"                                              
   V352 = "QJ13 BKT AMT IN/OUT STK"                                            
   V353 = "TOT SU INC"                                                         
   V354 = "AGE HD SU"                                                          
   V355 = "LIFE CYCLE"                                                         
   V356 = "NET WORTH"                                                          
   V357 = "WORK NOW/UNEM/RETIRED"                                              
   V358 = "OCCUP B:OCCUP WHEN WORK"                                            
   V359 = "OCCUP RE-GROUPED"                                                   
   V360 = "QA1 BET/WORSE FIN"                                                  
   V361 = "QA2 MORE/LESS MON NOW"                                              
   V362 = "QA1,A,2,A AFFECT FIN R1"                                            
   V363 = "QA1,A2  AFFECT FIN R2"                                              
   V364 = "QA3-3A EXP/UNEXP FIN"                                               
   V365 = "QA3A UNEXP-WHY"                                                     
   V366 = "QA4 GOOD/BAD YR"                                                    
   V367 = "QA4A WHY GD/BD YR R1"                                               
   V368 = "QA4A WHY GD/BD R2"                                                  
   V369 = "QA5 BET/WORSE 1 YR"                                                 
   V370 = "QA6 EARN UP/DOWN"                                                   
   V371 = "QA6A WHY EARN UP/DN R1"                                             
   V372 = "QA6A WHY EARN UP/DN R2"                                             
   V373 = "QA7  IMP/NT IMP INC MON"                                            
   V374 = "QA7A,B LIKE TO DO R1"                                               
   V375 = "QA7A,B LIKE TO DO R2"                                               
   V376 = "QA8 AV/LESS AV EARN"                                                
   V377 = "QA8A WHY AV/LESS EARN R1"                                           
   V378 = "QA8A WHY AV/LESS EARN R2"                                           
   V379 = "QA9,A EXTRA MON"                                                    
   V380 = "QA9,A WHAT SPEND ON R1"                                             
   V381 = "QA9,A WHAT SPEND ON R2"                                             
   V382 = "QA10,A PURP SAV R1"                                                 
   V383 = "QA10,A PURP SAV R2"                                                 
   V384 = "QA10 OTH REASONS SAV"                                               
   V385 = "QA10A WHICH IMP"                                                    
   V386 = "QA11 SAV INCR/DECR"                                                 
   V387 = "QA12 PRICES UP/DOWN"                                                
   V388 = "QA13 PRICES GD/BD"                                                  
   V389 = "QA14,A PRICE HGH/LWR"                                               
   V390 = "QA15 BUS COND GD/BD"                                                
   V391 = "QA15A WHY GD/BD R1"                                                 
   V392 = "QA15A WHY GD/BD R2"                                                 
   V393 = "QA16 BUS CON BT/WR"                                                 
   V394 = "QA17,A FAV/UNFAV CHNG R1"                                           
   V395 = "QA17,A FAV/UNFAV CHNG R2"                                           
   V396 = "QA18 MR/LESS UNEM"                                                  
   V397 = "QA18A WHY MR/LESS UNEM"                                             
   V398 = "QA19 BUS CON BT/WRS 1YR"                                            
   V399 = "QA20,A GD/BD NXT 5 YRS"                                             
   V400 = "QB16 GD/BD TIME BUY HS"                                             
   V401 = "QB16A WHY GD/BD  R1"                                                
   V402 = "QB16A WHY GD/BD  R2"                                                
   V403 = "QB17 EXP BY/BLD HS"                                                 
   V404 = "QB18 HOW MUCH TO BLD"                                               
   V405 = "QB27 EXP LARGE EXPD"                                                
   V406 = "EXP EXPD A AND R 12 MTHS"                                           
   V407 = "QC29 GD/BD BUY CAR"                                                 
   V408 = "QC30 WHY GD/BD BUY CAR"                                             
   V409 = "QC31 EXP BUY CAR 12 MTHS"                                           
   V410 = "QC32 NEW/USED CAR"                                                  
   V411 = "QC33 WHEN BUY CAR"                                                  
   V412 = "QC34 $HOW MUCH PAY CAR"                                             
   V413 = "QC34 BKT AMT PAY FOR CAR"                                           
   V414 = "QD11 GD/BD TIME BUY FURN"                                           
   V415 = "QD11A WHY GD/BD TIME R1"                                            
   V416 = "QD11A WHY GD/BD TIME R2"                                            
   V417 = "QD12-14 BUY LARGE ITEMS"                                            
   V418 = "QD15 $AMT EXP TO SPEND"                                             
   V419 = "QD15 BKT AMT EXP SPEND"                                             
   V420 = "QD14 BUY TELE"                                                      
   V421 = "QD15 BKT AMT ON TELE"                                               
   V422 = "QD14 BUY REFRIG"                                                    
   V423 = "QD15 BKT AMT SPD REFRIG"                                            
   V424 = "QD14 BUY WASH MACH"                                                 
   V425 = "QD15 BKT AMT SPD"                                                   
   V426 = "QD14 BUY FURN"                                                      
   V427 = "QD15 BKT COST"                                                      
   V428 = "QD14 BUY OTH DRBLS"                                                 
   V429 = "QG48 TOT SU INC"                                                    
   V430 = "FARMER/SECOND"                                                      
   V431 = "FAM UNIT"                                                           
   V432 = "SU INC"                                                             
   V433 = "NEW AGE-INC TRSLS"                                                  
   V434 = "TOT REM INSTAL DEBT"                                                
   V435 = "$CHNGE LIQ ASSETS"                                                  
   V436 = "MON IN/OUT STOCK"                                                   
   V437 = "CHANGE LIQ ASSETS/STOCK"                                            
   V438 = "FLD CHNG LIQ ASSETS"                                                
   V439 = "MON IN/OUT STOCK"                                                   
   V440 = "BKT LIQ ASSETS/STOCK"                                               
   V441 = "$LIQ ASSETS/STOCK"                                                  
   V442 = "FLD LIQ ASSETS/STOCK"                                               
   V443 = "NET WORTH"                                                          
   V444 = "NET VAR VAL ASSETS"                                                 
   V445 = "NET CONS-CAP GOODS"                                                 
   V446 = "$NET BUS/INVT ASSETS"                                               
   V447 = "$NET FIX VAL ASSETS"                                                
   V448 = "$MED DEBT"                                                          
   V449 = "$TOT OTH DEBTS"                                                     
   V450 = "NET WORTH"                                                          
   V451 = "NET VAR VAL ASSETS"                                                 
   V452 = "NET CON-CAP GOODS"                                                  
   V453 = "BKT NET BUS/INVEST ASSET"                                           
   V454 = "BKT NET FIX VAL ASSETS"                                             
   V455 = "BKT NET OTHER ASSETS"                                               
   V456 = "MEDICAL DEBT"                                                       
   V457 = "TOT OTHER DEBT"                                                     
   V458 = "$NET VAL OTH DEBT"                                                  
   V459 = "GROSS WORTH"                                                        
   V460 = "GROSS VAR VAL ASSETS"                                               
   V461 = "GROSS FIX VAL ASSETS"                                               
   V462 = "NET WORTH"                                                          
   V463 = "GROSS DEBT"                                                         
   V464 = "GROSS CONS CAP GOODS"                                               
   V465 = "GROSS BUS/INV ASSETS"                                               
   V466 = "SU TOT INC"                                                         
   V467 = "NETW/INC RATIO"                                                     
   V468 = "GROSS VAR VAL ASS/NETW"                                             
   V469 = "GROSS WORTH"                                                        
   V470 = "GROSS VAR VAL"                                                      
   V471 = "GROSS FIX VAL"                                                      
   V472 = "GROSS DEBT"                                                         
   V473 = "GROSS CONS CAP GOOD"                                                
   V474 = "GROSS BUS/INV"                                                      
   V475 = "NETW/INC RATIO"                                                     
   V476 = "GROSS VAR VAL AS/NET WRT"                                           
   V477 = "$ NON-FARM"                                                         
   V478 = "$RETAL VAL AUTO"                                                    
   V479 = "$VL FARM/HS/LVSK"                                                   
   V480 = "$VL OTH RE"                                                         
   V481 = "$VL UNINC/PRIV BUS"                                                 
   V482 = "$VL STKHLD"                                                         
   V483 = "$LQ ASSETS"                                                         
   V484 = "$VL OTH FIN ASSETS"                                                 
   V485 = "NON-FARM HM GROSS"                                                  
   V486 = "RET VAL AUTO GROSS"                                                 
   V487 = "VAL FARM/HS/LVSK"                                                   
   V488 = "VAL OTH RE"                                                         
   V489 = "VAL UNINC/PRIV BUS"                                                 
   V490 = "VAL STOCK HID GROSS"                                                
   V491 = "VAL LIQ ASSETS"                                                     
   V492 = "VAL OTH FIN ASSETS"                                                 
   V493 = "NO PEO INC CLASS"                                                   
   V494 = "NO ADLTS+ND CHILD SU"                                               
   V495 = "WEIGHTS";                                                           
                                                                               
* USER-DEFINED MISSING VALUE RECODE TO SAS SYSMIS;                             
                                                                               
/*                                                                             
   IF V1 LE -000009 THEN V1=.;         IF V2 LE -000009 THEN V2=.;             
   IF V3 GE 0000009 OR V3=0000000 THEN V3=.;                                   
   IF V4 GE 0000009 OR V4=0000000 THEN V4=.;                                   
   IF V5 LE -099999 OR V5=0000000 THEN V5=.;                                   
   IF V6 GE 0000009 OR V6=0000000 THEN V6=.;                                   
   IF V7 GE 0000009 OR V7=0000000 THEN V7=.;                                   
   IF V8 LE -099999 OR V8=0000000 THEN V8=.;                                   
   IF V9 GE 0000009 OR V9=0000000 THEN V9=.;                                   
   IF V10 GE 0000008 OR V10=0000000 THEN V10=.;                                
   IF V11 GE 0000009 OR V11=0000000 THEN V11=.;                                
   IF V12 GE 0000009 THEN V12=.;                                               
   IF V13 GE 0000009 OR V13=0000000 THEN V13=.;                                
   IF V14 GE 0000009 OR V14=0000000 THEN V14=.;                                
   IF V15 GE 0000009 OR V15=0000000 THEN V15=.;                                
   IF V16 GE 0000009 OR V16=0000000 THEN V16=.;                                
   IF V17 GE 0000009 OR V17=0000000 THEN V17=.;                                
   IF V18 LE -099999 OR V18=0000000 THEN V18=.;                                
   IF V19 GE 0000009 OR V19=0000000 THEN V19=.;                                
   IF V20 LE -099999 OR V20=0000000 THEN V20=.;                                
   IF V21 GE 0000009 OR V21=0000000 THEN V21=.;                                
   IF V22 GE 0000009 OR V22=0000000 THEN V22=.;                                
   IF V23 LE -099999 OR V23=0000000 THEN V23=.;                                
   IF V24 GE 0000009 OR V24=0000000 THEN V24=.;                                
   IF V25 GE 0000009 THEN V25=.;       IF V26 GE 0000008 THEN V26=.;           
   IF V27 GE 0000009 OR V27=0000000 THEN V27=.;                                
   IF V28 GE 0000009 THEN V28=.;       IF V29 GE 0000009 THEN V29=.;           
   IF V30 GE 0000009 OR V30=0000000 THEN V30=.;                                
   IF V31 GE 0000008 OR V31=0000000 THEN V31=.;                                
   IF V32 GE 0000008 OR V32=0000000 THEN V32=.;                                
   IF V33 GE 0000008 OR V33=0000000 THEN V33=.;                                
   IF V34 GE 0000008 OR V34=0000000 THEN V34=.;                                
   IF V35 LE -000009 THEN V35=.;       IF V36 GE 0000009 THEN V36=.;           
   IF V37 LE -000009 THEN V37=.;       IF V38 GE 0000009 THEN V38=.;           
   IF V39 GE 0000009 OR V39=0000000 THEN V39=.;                                
   IF V40 GE 0000008 OR V40=0000000 THEN V40=.;                                
   IF V41 GE 0000009 THEN V41=.;                                               
   IF V42 GE 0000009 OR V42=0000000 THEN V42=.;                                
   IF V43 GE 0000008 OR V43=0000000 THEN V43=.;                                
   IF V44 GE 0000009 THEN V44=.;       IF V45 LE -000009 THEN V45=.;           
   IF V46 LE -000009 THEN V46=.;       IF V47 GE 0000009 THEN V47=.;           
   IF V48 GE 0000009 THEN V48=.;       IF V49 LE -000009 THEN V49=.;           
   IF V50 GE 0000099 THEN V50=.;       IF V51=-9 THEN V51= " ";                
   IF V52 GE 0000099 THEN V52=.;       IF V53 LE -000009 THEN V53=.;           
   IF V54 GE 0000009 THEN V54=.;       IF V55 GE 0000099 THEN V55=.;           
   IF V56 GE 0000009 THEN V56=.;                                               
   IF V57 GE 0000099 OR V57=0000000 THEN V57=.;                                
   IF V58 GE 0000009 OR V58=0000000 THEN V58=.;                                
   IF V59 GE 0000009 THEN V59=.;       IF V60 GE 0000009 THEN V60=.;           
   IF V61 GE 0000009 THEN V61=.;       IF V62 GE 0000009 THEN V62=.;           
   IF V63 GE 0000009 OR V63=0000000 THEN V63=.;                                
   IF V64 GE 0000009 OR V64=0000000 THEN V64=.;                                
   IF V65 GE 0000009 OR V65=0000000 THEN V65=.;                                
   IF V66 GE 0000009 THEN V66=.;                                               
   IF V67 GE 0000009 OR V67=0000000 THEN V67=.;                                
   IF V68 GE 0000009 OR V68=0000000 THEN V68=.;                                
   IF V69 GE 0000009 THEN V69=.;       IF V70 GE 0000009 THEN V70=.;           
   IF V71 GE 0000009 OR V71=0000000 THEN V71=.;                                
   IF V72 GE 0000009 THEN V72=.;                                               
   IF V73 GE 0000009 OR V73=0000000 THEN V73=.;                                
   IF V74 GE 0000009 THEN V74=.;       IF V75 GE 0000009 THEN V75=.;           
   IF V76 GE 0000009 THEN V76=.;       IF V77 GE 0000009 THEN V77=.;           
   IF V78 GE 0000009 THEN V78=.;                                               
   IF V79 GE 0000009 OR V79=0000000 THEN V79=.;                                
   IF V80 GE 0000009 OR V80=0000000 THEN V80=.;                                
   IF V81 GE 0000009 OR V81=0000000 THEN V81=.;                                
   IF V82 LE -000009 THEN V82=.;                                               
   IF V83 GE 0000009 OR V83=0000000 THEN V83=.;                                
   IF V84 GE 0000009 THEN V84=.;       IF V85 GE 0000009 THEN V85=.;           
   IF V86 LE -000009 OR V86=0000000 THEN V86=.;                                
   IF V87 GE 0000009 THEN V87=.;       IF V88 LE -000009 THEN V88=.;           
   IF V89 GE 0000009 THEN V89=.;       IF V90 LE -000009 THEN V90=.;           
   IF V91 GE 0000009 THEN V91=.;       IF V92 LE -000009 THEN V92=.;           
   IF V93 LE -000009 THEN V93=.;       IF V94 LE -000009 THEN V94=.;           
   IF V95 GE 0000009 THEN V95=.;                                               
   IF V96 LE -000009 OR V96=0000000 THEN V96=.;                                
   IF V97 GE 0000009 THEN V97=.;       IF V98 GE 0000009 THEN V98=.;           
   IF V99 LE -000009 THEN V99=.;       IF V100 GE 0000009 THEN V100=.;         
   IF V101 LE -000009 THEN V101=.;                                             
   IF V102 GE 0000009 OR V102=0000000 THEN V102=.;                             
   IF V103 GE 0000009 THEN V103=.;                                             
   IF V104 GE 0000009 OR V104=0000000 THEN V104=.;                             
   IF V105 LE -000099 OR V105=0000000 THEN V105=.;                             
   IF V106 GE 0000009 OR V106=0000000 THEN V106=.;                             
   IF V107 LE -000009 OR V107=0000000 THEN V107=.;                             
   IF V108 LE -000009 OR V108=0000000 THEN V108=.;                             
   IF V109 GE 0000009 OR V109=0000000 THEN V109=.;                             
   IF V110 GE 0000009 OR V110=0000000 THEN V110=.;                             
   IF V111 GE 0000009 OR V111=0000000 THEN V111=.;                             
   IF V112 LE -000009 OR V112=0000000 THEN V112=.;                             
   IF V113 GE 0000009 OR V113=0000000 THEN V113=.;                             
   IF V114 LE -000099 OR V114=0000000 THEN V114=.;                             
   IF V115 GE 0000009 OR V115=0000000 THEN V115=.;                             
   IF V116 LE -000099 OR V116=0000000 THEN V116=.;                             
   IF V117 GE 0000009 OR V117=0000000 THEN V117=.;                             
   IF V118 GE 0000099 OR V118=0000000 THEN V118=.;                             
   IF V119 GE 0000009 OR V119=0000000 THEN V119=.;                             
   IF V120 GE 0000009 OR V120=0000000 THEN V120=.;                             
   IF V121 LE -000999 OR V121=0000000 THEN V121=.;                             
   IF V122 GE 0000009 OR V122=0000000 THEN V122=.;                             
   IF V123 GE 0000009 OR V123=0000000 THEN V123=.;                             
   IF V124 LE -009999 OR V124=0000000 THEN V124=.;                             
   IF V125 GE 0000009 OR V125=0000000 THEN V125=.;                             
   IF V126 GE 0000009 OR V126=0000000 THEN V126=.;                             
   IF V127 GE 0000009 THEN V127=.;     IF V128 GE 0000009 THEN V128=.;         
   IF V129 GE 0000009 THEN V129=.;                                             
   IF V130 LE -000009 OR V130=0000000 THEN V130=.;                             
   IF V131 GE 0000009 OR V131=0000000 THEN V131=.;                             
   IF V132 GE 0000009 THEN V132=.;     IF V133 GE 0000009 THEN V133=.;         
   IF V134 GE 0000009 THEN V134=.;     IF V135 GE 0000009 THEN V135=.;         
   IF V136 LE -000009 THEN V136=.;     IF V137 LE -000009 THEN V137=.;         
   IF V138 GE 0000009 THEN V138=.;     IF V139 GE 0000009 THEN V139=.;         
   IF V140 GE 0000009 OR V140=0000000 THEN V140=.;                             
   IF V141 GE 0000009 OR V141=0000000 THEN V141=.;                             
   IF V142 GE 0000010 THEN V142=.;     IF V143 GE 0000005 THEN V143=.;         
   IF V144 LE -000009 OR V144=0000000 THEN V144=.;                             
   IF V145 GE 0000009 OR V145=0000000 THEN V145=.;                             
   IF V146 GE 0000099 OR V146=0000000 THEN V146=.;                             
   IF V147 GE 0000099 OR V147=0000000 THEN V147=.;                             
   IF V148 GE 0000009 OR V148=0000000 THEN V148=.;                             
   IF V149 GE 0000009 OR V149=0000000 THEN V149=.;                             
   IF V150 GE 0000099 OR V150=0000000 THEN V150=.;                             
   IF V151 GE 0000009 OR V151=0000000 THEN V151=.;                             
   IF V152 GE 0000009 OR V152=0000000 THEN V152=.;                             
   IF V153 GE 0000099 OR V153=0000000 THEN V153=.;                             
   IF V154 GE 0000099 OR V154=0000000 THEN V154=.;                             
   IF V155 GE 0000009 OR V155=0000000 THEN V155=.;                             
   IF V156 GE 0000099 OR V156=0000000 THEN V156=.;                             
   IF V157 GE 0000009 OR V157=0000000 THEN V157=.;                             
   IF V158 LE -000009 OR V158=0000000 THEN V158=.;                             
   IF V159 LE -000009 OR V159=0000000 THEN V159=.;                             
   IF V160 LE -000009 OR V160=0000000 THEN V160=.;                             
   IF V161 LE -000009 OR V161=0000000 THEN V161=.;                             
   IF V162 LE -000009 OR V162=0000000 THEN V162=.;                             
   IF V163 LE -000009 OR V163=0000000 THEN V163=.;                             
   IF V164 LE -000999 OR V164=0000000 THEN V164=.;                             
   IF V165 GE 0000009 OR V165=0000000 THEN V165=.;                             
   IF V166 LE -000999 OR V166=0000000 THEN V166=.;                             
   IF V167 GE 0000009 OR V167=0000000 THEN V167=.;                             
   IF V168 LE -000999 OR V168=0000000 THEN V168=.;                             
   IF V169 GE 0000009 OR V169=0000000 THEN V169=.;                             
   IF V170 GE 0000009 OR V170=0000000 THEN V170=.;                             
   IF V171 LE -000099 OR V171=0000000 THEN V171=.;                             
   IF V172 GE 0000009 OR V172=0000000 THEN V172=.;                             
   IF V173 GE 0000099 OR V173=0000000 THEN V173=.;                             
   IF V174 GE 0000099 OR V174=0000000 THEN V174=.;                             
   IF V175 GE 0000009 OR V175=0000000 THEN V175=.;                             
   IF V176 GE 0000009 OR V176=0000000 THEN V176=.;                             
   IF V177 GE 0000009 OR V177=0000000 THEN V177=.;                             
   IF V178 GE 0000009 OR V178=0000000 THEN V178=.;                             
   IF V179 GE 0000009 OR V179=0000000 THEN V179=.;                             
   IF V180 GE 0000009 OR V180=0000000 THEN V180=.;                             
   IF V181 GE 0000009 OR V181=0000000 THEN V181=.;                             
   IF V182 GE 0000009 OR V182=0000000 THEN V182=.;                             
   IF V183 GE 0000009 THEN V183=.;     IF V184 GE 0000009 THEN V184=.;         
   IF V185 GE 0000009 THEN V185=.;     IF V186 LE -000009 THEN V186=.;         
   IF V187 LE -000999 OR V187=0000000 THEN V187=.;                             
   IF V188 GE 0000009 OR V188=0000000 THEN V188=.;                             
   IF V189 LE -000999 OR V189=0000000 THEN V189=.;                             
   IF V190 GE 0000009 OR V190=0000000 THEN V190=.;                             
   IF V191 LE -000999 OR V191=0000000 THEN V191=.;                             
   IF V192 GE 0000009 OR V192=0000000 THEN V192=.;                             
   IF V193 GE 0000009 OR V193=0000000 THEN V193=.;                             
   IF V194 GE 0000009 OR V194=0000000 THEN V194=.;                             
   IF V195 GE 0000009 OR V195=0000000 THEN V195=.;                             
   IF V196 GE 0000009 OR V196=0000000 THEN V196=.;                             
   IF V197 GE 0000009 OR V197=0000000 THEN V197=.;                             
   IF V198 GE 0000009 OR V198=0000000 THEN V198=.;                             
   IF V199 GE 0000009 OR V199=0000000 THEN V199=.;                             
   IF V200 GE 0000009 OR V200=0000000 THEN V200=.;                             
   IF V201 GE 0000009 OR V201=0000000 THEN V201=.;                             
   IF V202 GE 0000009 OR V202=0000000 THEN V202=.;                             
   IF V203 GE 0000009 OR V203=0000000 THEN V203=.;                             
   IF V204 GE 0000009 THEN V204=.;                                             
   IF V205 GE 0000009 OR V205=0000000 THEN V205=.;                             
   IF V206 GE 0000009 OR V206=0000000 THEN V206=.;                             
   IF V207 GE 0000009 OR V207=0000000 THEN V207=.;                             
   IF V208 GE 0000009 OR V208=0000000 THEN V208=.;                             
   IF V209 LE -000999 OR V209=0000000 THEN V209=.;                             
   IF V210 GE 0000009 OR V210=0000000 THEN V210=.;                             
   IF V211 LE -000009 OR V211=0000000 THEN V211=.;                             
   IF V212 LE -000009 OR V212=0000000 THEN V212=.;                             
   IF V213 LE -009999 OR V213=0000000 THEN V213=.;                             
   IF V214 GE 0000009 OR V214=0000000 THEN V214=.;                             
   IF V215 LE -000999 OR V215=0000000 THEN V215=.;                             
   IF V216 GE 0000009 OR V216=0000000 THEN V216=.;                             
   IF V217 LE -009999 OR V217=0000000 THEN V217=.;                             
   IF V218 GE 0000009 OR V218=0000000 THEN V218=.;                             
   IF V219 GE 0000009 THEN V219=.;     IF V220 GE 0000009 THEN V220=.;         
   IF V221 GE 0000009 THEN V221=.;     IF V222 LE -000009 THEN V222=.;         
   IF V223 GE 0000009 THEN V223=.;     IF V224 LE -000009 THEN V224=.;         
   IF V225 GE 0000009 THEN V225=.;     IF V226 GE 0000009 THEN V226=.;         
   IF V227 GE 0000009 THEN V227=.;     IF V228 GE 0000009 THEN V228=.;         
   IF V229 LE -000009 THEN V229=.;     IF V230 GE 0000009 THEN V230=.;         
   IF V231 LE -000009 OR V231=0000000 THEN V231=.;                             
   IF V232 LE -000009 OR V232=0000000 THEN V232=.;                             
   IF V233 LE -000009 OR V233=0000000 THEN V233=.;                             
   IF V234 LE -000009 OR V234=0000000 THEN V234=.;                             
   IF V235 LE -000099 OR V235=0000000 THEN V235=.;                             
   IF V236 LE -000009 OR V236=0000000 THEN V236=.;                             
   IF V237 LE -000999 OR V237=0000000 THEN V237=.;                             
   IF V238 GE 0000009 OR V238=0000000 THEN V238=.;                             
   IF V239 GE 0000009 OR V239=0000000 THEN V239=.;                             
   IF V240 GE 0000009 OR V240=0000000 THEN V240=.;                             
   IF V241 GE 0000009 OR V241=0000000 THEN V241=.;                             
   IF V242 GE 0000009 OR V242=0000000 THEN V242=.;                             
   IF V243 GE 0000009 OR V243=0000000 THEN V243=.;                             
   IF V244 GE 0000009 OR V244=0000000 THEN V244=.;                             
   IF V245 GE 0000009 OR V245=0000000 THEN V245=.;                             
   IF V246 GE 0000009 OR V246=0000000 THEN V246=.;                             
   IF V247 GE 0000009 OR V247=0000000 THEN V247=.;                             
   IF V248 GE 0000009 OR V248=0000000 THEN V248=.;                             
   IF V249 GE 0000009 OR V249=0000000 THEN V249=.;                             
   IF V250 GE 0000009 OR V250=0000000 THEN V250=.;                             
   IF V251 GE 0000009 OR V251=0000000 THEN V251=.;                             
   IF V252 LE -000999 OR V252=0000000 THEN V252=.;                             
   IF V253 GE 0000009 OR V253=0000000 THEN V253=.;                             
   IF V254 LE -000009 OR V254=0000000 THEN V254=.;                             
   IF V255 LE -000009 THEN V255=.;                                             
   IF V256 LE -000099 OR V256=0000000 THEN V256=.;                             
   IF V257 GE 0000009 OR V257=0000000 THEN V257=.;                             
   IF V258 LE -000009 OR V258=0000000 THEN V258=.;                             
   IF V259 LE -000009 OR V259=0000000 THEN V259=.;                             
   IF V260 LE -000009 OR V260=0000000 THEN V260=.;                             
   IF V261 LE -000009 OR V261=0000000 THEN V261=.;                             
   IF V262 LE -000009 OR V262=0000000 THEN V262=.;                             
   IF V263 LE -000009 OR V263=0000000 THEN V263=.;                             
   IF V264 LE -000009 OR V264=0000000 THEN V264=.;                             
   IF V265 LE -000009 THEN V265=.;     IF V266 LE -000009 THEN V266=.;         
   IF V267 LE -000009 THEN V267=.;     IF V268 LE -000009 THEN V268=.;         
   IF V269 LE -000009 THEN V269=.;                                             
   IF V270 GE 0000009 OR V270=0000000 THEN V270=.;                             
   IF V271 GE 0000009 OR V271=0000000 THEN V271=.;                             
   IF V272 GE 0000009 OR V272=0000000 THEN V272=.;                             
   IF V273 GE 0000009 OR V273=0000000 THEN V273=.;                             
   IF V274 GE 0000009 OR V274=0000000 THEN V274=.;                             
   IF V275 GE 0000009 OR V275=0000000 THEN V275=.;                             
   IF V276 LE -000009 OR V276=0000000 THEN V276=.;                             
   IF V277 GE 0000009 OR V277=0000000 THEN V277=.;                             
   IF V278 GE 0000009 OR V278=0000000 THEN V278=.;                             
   IF V279 GE 0000009 OR V279=0000000 THEN V279=.;                             
   IF V280 GE 0000009 OR V280=0000000 THEN V280=.;                             
   IF V281 GE 0000009 OR V281=0000000 THEN V281=.;                             
   IF V282 GE 0000009 OR V282=0000000 THEN V282=.;                             
   IF V283 GE 0000008 OR V283=0000000 THEN V283=.;                             
   IF V284 GE 0000009 OR V284=0000000 THEN V284=.;                             
   IF V285 GE 0000009 THEN V285=.;     IF V286 GE 0000009 THEN V286=.;         
   IF V287 LE -000009 THEN V287=.;     IF V288 LE -000009 THEN V288=.;         
   IF V289 GE 0000009 THEN V289=.;     IF V290 GE 0000009 THEN V290=.;         
   IF V291 GE 0000009 OR V291=0000000 THEN V291=.;                             
   IF V292 GE 0000009 OR V292=0000000 THEN V292=.;                             
   IF V293 GE 0000098 THEN V293=.;                                             
   IF V294 LE -000009 OR V294=0000000 THEN V294=.;                             
   IF V295 GE 0000009 OR V295=0000000 THEN V295=.;                             
   IF V296 GE 0000009 OR V296=0000000 THEN V296=.;                             
   IF V297 GE 0000008 OR V297=0000000 THEN V297=.;                             
   IF V298 GE 0000008 OR V298=0000000 THEN V298=.;                             
   IF V299 GE 0000008 OR V299=0000000 THEN V299=.;                             
   IF V300 GE 0000008 OR V300=0000000 THEN V300=.;                             
   IF V301 GE 0000009 OR V301=0000000 THEN V301=.;                             
   IF V302 GE 0000009 OR V302=0000000 THEN V302=.;                             
   IF V303 LE -009999 OR V303=0000000 THEN V303=.;                             
   IF V304 GE 0000009 OR V304=0000000 THEN V304=.;                             
   IF V305 LE -009999 OR V305=0000000 THEN V305=.;                             
   IF V306 GE 0000009 OR V306=0000000 THEN V306=.;                             
   IF V307 GE 0000009 OR V307=0000000 THEN V307=.;                             
   IF V308 GE 0000009 THEN V308=.;                                             
   IF V309 LE -000009 OR V309=0000000 THEN V309=.;                             
   IF V310 GE 0000009 OR V310=0000000 THEN V310=.;                             
   IF V311 GE 0000009 OR V311=0000000 THEN V311=.;                             
   IF V312 LE -099999 OR V312=0000000 THEN V312=.;                             
   IF V313 GE 0000009 OR V313=0000000 THEN V313=.;                             
   IF V314 LE -099999 OR V314=0000000 THEN V314=.;                             
   IF V315 GE 0000009 OR V315=0000000 THEN V315=.;                             
   IF V316 GE 0000009 THEN V316=.;                                             
   IF V317 LE -099999 OR V317=0000000 THEN V317=.;                             
   IF V318 GE 0000009 THEN V318=.;     IF V319 GE 0000009 THEN V319=.;         
   IF V320 LE -000009 THEN V320=.;     IF V321 LE -000009 THEN V321=.;         
   IF V322 LE -000009 THEN V322=.;     IF V323 GE 0000009 THEN V323=.;         
   IF V324 GE 0000009 THEN V324=.;     IF V325 GE 0000009 THEN V325=.;         
   IF V326 GE 0000009 THEN V326=.;     IF V327 LE -000009 THEN V327=.;         
   IF V328 GE 0000009 OR V328=0000000 THEN V328=.;                             
   IF V329 GE 0000009 OR V329=0000000 THEN V329=.;                             
   IF V330 GE 0000009 THEN V330=.;     IF V331 GE 0000009 THEN V331=.;         
   IF V332 LE -000009 OR V332=0000000 THEN V332=.;                             
   IF V333 GE 0000008 OR V333=0000000 THEN V333=.;                             
   IF V334 GE 0000009 THEN V334=.;     IF V335 GE 0000009 THEN V335=.;         
   IF V336 GE 0000009 THEN V336=.;                                             
   IF V337 LE -000009 OR V337=0000000 THEN V337=.;                             
   IF V338 GE 0000009 OR V338=0000000 THEN V338=.;                             
   IF V339 GE 0000009 OR V339=0000000 THEN V339=.;                             
   IF V340 LE -000009 OR V340=0000000 THEN V340=.;                             
   IF V341 GE 0000009 OR V341=0000000 THEN V341=.;                             
   IF V342 LE -000009 OR V342=0000000 THEN V342=.;                             
   IF V343 GE 0000009 OR V343=0000000 THEN V343=.;                             
   IF V344 GE 0000009 OR V344=0000000 THEN V344=.;                             
   IF V345 LE -000009 OR V345=0000000 THEN V345=.;                             
   IF V346 GE 0000009 OR V346=0000000 THEN V346=.;                             
   IF V347 GE 0000009 OR V347=0000000 THEN V347=.;                             
   IF V348 GE 0000009 THEN V348=.;     IF V349 GE 0000008 THEN V349=.;         
   IF V350 GE 0000009 OR V350=0000000 THEN V350=.;                             
   IF V351 GE 0000008 OR V351=0000000 THEN V351=.;                             
   IF V352 GE 0000009 OR V352=0000000 THEN V352=.;                             
   IF V353 LE -000009 THEN V353=.;     IF V354 GE 0000009 THEN V354=.;         
   IF V355 LE -000009 THEN V355=.;                                             
   IF V356 LE -000009 OR V356=0000000 THEN V356=.;                             
   IF V357 GE 0000009 THEN V357=.;     IF V358 LE -000009 THEN V358=.;         
   IF V359 GE 0000009 THEN V359=.;     IF V360 GE 0000009 THEN V360=.;         
   IF V361 GE 0000009 THEN V361=.;     IF V362 LE -000009 THEN V362=.;         
   IF V363 LE -000009 THEN V363=.;     IF V364 GE 0000009 THEN V364=.;         
   IF V365 GE 0000009 OR V365=0000000 THEN V365=.;                             
   IF V366 GE 0000009 THEN V366=.;                                             
   IF V367 LE -000009 OR V367=0000000 THEN V367=.;                             
   IF V368 LE -000009 OR V368=0000000 THEN V368=.;                             
   IF V369 GE 0000008 THEN V369=.;                                             
   IF V370 GE 0000008 OR V370=0000000 THEN V370=.;                             
   IF V371 LE -000009 OR V371=0000000 THEN V371=.;                             
   IF V372 LE -000009 OR V372=0000000 THEN V372=.;                             
   IF V373 GE 0000008 THEN V373=.;                                             
   IF V374 GE 0000099 OR V374=0000000 THEN V374=.;                             
   IF V375 GE 0000099 OR V375=0000000 THEN V375=.;                             
   IF V376 GE 0000008 THEN V376=.;                                             
   IF V377 GE 0000088 OR V377=0000000 THEN V377=.;                             
   IF V378 GE 0000088 OR V378=0000000 THEN V378=.;                             
   IF V379 GE 0000009 OR V379=0000000 THEN V379=.;                             
   IF V380 GE 0000009 OR V380=0000000 THEN V380=.;                             
   IF V381 GE 0000009 OR V381=0000000 THEN V381=.;                             
   IF V382 GE 0000009 OR V382=0000000 THEN V382=.;                             
   IF V383 GE 0000009 OR V383=0000000 THEN V383=.;                             
   IF V384 GE 0000009 OR V384=0000000 THEN V384=.;                             
   IF V385 GE 0000009 OR V385=0000000 THEN V385=.;                             
   IF V386 GE 0000008 THEN V386=.;     IF V387 GE 0000008 THEN V387=.;         
   IF V388 GE 0000008 OR V388=0000000 THEN V388=.;                             
   IF V389 GE 0000009 OR V389=0000000 THEN V389=.;                             
   IF V390 GE 0000008 THEN V390=.;                                             
   IF V391 GE 0000098 OR V391=0000000 THEN V391=.;                             
   IF V392 GE 0000098 OR V392=0000000 THEN V392=.;                             
   IF V393 GE 0000008 THEN V393=.;                                             
   IF V394 GE 0000099 OR V394=0000000 THEN V394=.;                             
   IF V395 GE 0000099 OR V395=0000000 THEN V395=.;                             
   IF V396 GE 0000008 THEN V396=.;                                             
   IF V397 GE 0000008 OR V397=0000000 THEN V397=.;                             
   IF V398 GE 0000008 THEN V398=.;                                             
   IF V399 GE 0000009 OR V399=0000000 THEN V399=.;                             
   IF V400 GE 0000008 THEN V400=.;                                             
   IF V401 GE 0000099 OR V401=0000000 THEN V401=.;                             
   IF V402 GE 0000099 OR V402=0000000 THEN V402=.;                             
   IF V403 GE 0000008 THEN V403=.;                                             
   IF V404 GE 0000009 OR V404=0000000 THEN V404=.;                             
   IF V405 GE 0000009 THEN V405=.;                                             
   IF V406 GE 0000009 OR V406=0000000 THEN V406=.;                             
   IF V407 GE 0000008 THEN V407=.;                                             
   IF V408 GE 0000098 OR V408=0000000 THEN V408=.;                             
   IF V409 GE 0000008 THEN V409=.;                                             
   IF V410 GE 0000009 OR V410=0000000 THEN V410=.;                             
   IF V411 GE 0000009 OR V411=0000000 THEN V411=.;                             
   IF V412 LE -000999 OR V412=0000000 THEN V412=.;                             
   IF V413 GE 0000009 OR V413=0000000 THEN V413=.;                             
   IF V414 GE 0000008 THEN V414=.;                                             
   IF V415 GE 0000099 OR V415=0000000 THEN V415=.;                             
   IF V416 GE 0000099 OR V416=0000000 THEN V416=.;                             
   IF V417 GE 0000009 THEN V417=.;                                             
   IF V418 LE -000999 OR V418=0000000 THEN V418=.;                             
   IF V419 GE 0000009 OR V419=0000000 THEN V419=.;                             
   IF V420 LE -000009 OR V420=0000000 THEN V420=.;                             
   IF V421 GE 0000009 OR V421=0000000 THEN V421=.;                             
   IF V422 LE -000009 OR V422=0000000 THEN V422=.;                             
   IF V423 GE 0000009 OR V423=0000000 THEN V423=.;                             
   IF V424 LE -000009 OR V424=0000000 THEN V424=.;                             
   IF V425 GE 0000009 OR V425=0000000 THEN V425=.;                             
   IF V426 LE -000009 OR V426=0000000 THEN V426=.;                             
   IF V427 GE 0000009 OR V427=0000000 THEN V427=.;                             
   IF V428 GE 0000009 OR V428=0000000 THEN V428=.;                             
   IF V429 LE -000009 THEN V429=.;     IF V430 GE 0000009 THEN V430=.;         
   IF V431 LE -000009 THEN V431=.;     IF V432 GE 0000009 THEN V432=.;         
   IF V433 LE -000009 THEN V433=.;     IF V434 GE 0000009 THEN V434=.;         
   IF V435 LE -000009 THEN V435=.;     IF V436 LE -000009 THEN V436=.;         
   IF V437 LE -000009 THEN V437=.;     IF V438 GE 0000010 THEN V438=.;         
   IF V439 GE 0000010 THEN V439=.;     IF V440 GE 0000010 THEN V440=.;         
   IF V441 LE -000009 THEN V441=.;                                             
   IF V442 GE 0000009 OR V442=0000000 THEN V442=.;                             
   IF V443 LE -000009 OR V443=0000000 THEN V443=.;                             
   IF V444 LE -000009 OR V444=0000000 THEN V444=.;                             
   IF V445 LE -000009 OR V445=0000000 THEN V445=.;                             
   IF V446 LE -000009 OR V446=0000000 THEN V446=.;                             
   IF V447 LE -000009 OR V447=0000000 THEN V447=.;                             
   IF V448 LE -000009 OR V448=0000000 THEN V448=.;                             
   IF V449 LE -000009 OR V449=0000000 THEN V449=.;                             
   IF V450 GE 0000009 OR V450=0000000 THEN V450=.;                             
   IF V451 GE 0000009 OR V451=0000000 THEN V451=.;                             
   IF V452 GE 0000009 OR V452=0000000 THEN V452=.;                             
   IF V453 GE 0000009 OR V453=0000000 THEN V453=.;                             
   IF V454 GE 0000009 OR V454=0000000 THEN V454=.;                             
   IF V455 GE 0000009 OR V455=0000000 THEN V455=.;                             
   IF V456 GE 0000009 OR V456=0000000 THEN V456=.;                             
   IF V457 GE 0000009 OR V457=0000000 THEN V457=.;                             
   IF V458 LE -000009 OR V458=0000000 THEN V458=.;                             
   IF V459 LE -000009 OR V459=0000000 THEN V459=.;                             
   IF V460 LE -000009 OR V460=0000000 THEN V460=.;                             
   IF V461 LE -000009 OR V461=0000000 THEN V461=.;                             
   IF V462 LE -000009 OR V462=0000000 THEN V462=.;                             
   IF V463 LE -000009 OR V463=0000000 THEN V463=.;                             
   IF V464 LE -000009 OR V464=0000000 THEN V464=.;                             
   IF V465 LE -000009 OR V465=0000000 THEN V465=.;                             
   IF V466 LE -000009 OR V466=0000000 THEN V466=.;                             
   IF V467=0000000 THEN V467=.;        IF V468=0000000 THEN V468=.;            
   IF V469 GE 0000009 OR V469=0000000 THEN V469=.;                             
   IF V470 GE 0000009 OR V470=0000000 THEN V470=.;                             
   IF V471 GE 0000009 OR V471=0000000 THEN V471=.;                             
   IF V472 GE 0000009 OR V472=0000000 THEN V472=.;                             
   IF V473 GE 0000009 OR V473=0000000 THEN V473=.;                             
   IF V474 GE 0000009 OR V474=0000000 THEN V474=.;                             
   IF V475 GE 0000009 OR V475=0000000 THEN V475=.;                             
   IF V476 GE 0000009 THEN V476=.;                                             
   IF V477 LE -000009 OR V477=0000000 THEN V477=.;                             
   IF V478 LE -000009 OR V478=0000000 THEN V478=.;                             
   IF V479 LE -000009 OR V479=0000000 THEN V479=.;                             
   IF V480 LE -000009 OR V480=0000000 THEN V480=.;                             
   IF V481 LE -000009 OR V481=0000000 THEN V481=.;                             
   IF V482 LE -000009 OR V482=0000000 THEN V482=.;                             
   IF V483 LE -000009 OR V483=0000000 THEN V483=.;                             
   IF V484 LE -000009 OR V484=0000000 THEN V484=.;                             
   IF V485 LE -000009 OR V485=0000000 THEN V485=.;                             
   IF V486 LE -000009 OR V486=0000000 THEN V486=.;                             
   IF V487 GE 0000009 OR V487=0000000 THEN V487=.;                             
   IF V488 GE 0000009 OR V488=0000000 THEN V488=.;                             
   IF V489 GE 0000009 OR V489=0000000 THEN V489=.;                             
   IF V490 GE 0000009 OR V490=0000000 THEN V490=.;                             
   IF V491 GE 0000009 OR V491=0000000 THEN V491=.;                             
   IF V492 GE 0000009 OR V492=0000000 THEN V492=.;                             
   IF V493 LE -000009 THEN V493=.;     IF V494 GE 0000009 THEN V494=.;         
   IF V495 LE -000009 THEN V495=.;                                             
*/                                                                             
